const CONFIG=window.AG_WORLD_CONFIG||{};
let farms=[],map=null,selected=null,scene=null,renderer=null,camera=null,animationId=null,sceneFarm=null,sceneObjects=[];
let drawingManager=null,newBoundary=[],boundaryPolygon=null,creatingFarm=false;
const $=id=>document.getElementById(id);
const toast=m=>{const t=$("toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)};
async function loadFarms(){try{const r=await fetch("data/farms.json");if(!r.ok)throw Error();farms=(await r.json()).farms||[];initMap()}catch(e){$("mapStatus").textContent="Farm data could not be loaded."}}
function initMap(){if(!CONFIG.GOOGLE_MAPS_API_KEY){$("mapStatus").textContent="Google satellite mapping is configured but inactive: add the API key in config.js.";return}const s=document.createElement("script");s.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(CONFIG.GOOGLE_MAPS_API_KEY)}&libraries=drawing&callback=agWorldMapReady`;s.async=true;s.defer=true;document.head.appendChild(s)}
window.agWorldMapReady=()=>{map=new google.maps.Map($("map"),{center:{lat:-29,lng:24},zoom:5,mapTypeId:"satellite",fullscreenControl:false,streetViewControl:false,mapTypeControl:false,gestureHandling:"greedy",tilt:0,rotateControl:false});map.addListener("zoom_changed",updateZoomStage);farms.forEach(addFarm);updateZoomStage();$("mapStatus").textContent="Satellite map active · farm records loaded"};
function addFarm(f){const p=new google.maps.Polygon({paths:f.boundary,strokeOpacity:.9,strokeWeight:2,fillOpacity:.16,map,clickable:true});p.addListener("click",()=>selectFarm(f,true));const m=new google.maps.Marker({position:f.center,map,title:f.name,label:{text:"AG",color:"#fff",fontSize:"9px",fontWeight:"700"}});m.addListener("click",()=>selectFarm(f,true));f._polygon=p;f._marker=m}
function updateZoomStage(){if(!map)return;const z=map.getZoom();let stage=z<7?1:z<9?2:z<12?3:4;$("zoomStage").textContent=`ZOOM ${stage} · ${["NATIONAL OVERVIEW","REGIONAL FARMS","FARM BOUNDARY","INTERACTIVE FARM"][stage-1]}`;if(stage>=3&&selected)showFarmDetail(selected)}
function selectFarm(f,zoom=true){if(creatingFarm)return;selected=f;$("farmCard").classList.add("show");$("farmName").textContent=f.name;$("farmMeta").textContent=`${f.region} · ${f.status} · ${f.owner}`;$("farmDrones").textContent=f.drones;$("farmTractors").textContent=f.tractors;$("farmCrops").textContent=(f.crops||[]).length;$("farmScore").textContent=f.opportunityScore??"—";$("farmLivestock").textContent=f.livestock??"—";$("farmHarvest").textContent=f.annualHarvest??"—";$("farmService").textContent=f.lastService??"—";$("farmDetailText").textContent=`Crops: ${(f.crops||[]).join(", ")||"Not recorded"}. ${f.drones?`${f.drones} company drone asset${f.drones===1?"":"s"} recorded.`:"No company drone recorded — commercial opportunity."}`;$("aiText").textContent=f.drones===0?`${f.name} has no company drone recorded and scores ${f.opportunityScore??"—"}/100. Qualify this opportunity and move the territory forward.`:`${f.name} is an active relationship. Protect the account through service quality and customer satisfaction.`;if(map&&zoom){map.panTo(f.center);map.setZoom(12)}showFarmDetail(f)}
function showFarmDetail(f){if(map&&map.getZoom()>=9)$("mapStatus").textContent=`Farm selected · ${f.name} · boundary linked to record ${f.id}`}
function national(){if(map){map.setCenter({lat:-29,lng:24});map.setZoom(5);$("farmCard").classList.remove("show");selected=null}}
function openCreateFarm(){if(!map){toast("Add the Google Maps API key first.");return}creatingFarm=true;newBoundary=[];if(boundaryPolygon){boundaryPolygon.setMap(null);boundaryPolygon=null}$("farmCreateModal").classList.add("show");$("boundaryStatus").textContent="Click START BOUNDARY, then draw the farm polygon on the map.";toast("Create Farm mode ready")}
function startBoundary(){if(!map)return;creatingFarm=true;$("farmCreateModal").classList.remove("show");$("mapStatus").textContent="DRAWING MODE · click the farm boundary points on the satellite map";map.setOptions({draggableCursor:"crosshair"});newBoundary=[];if(boundaryPolygon){boundaryPolygon.setMap(null);boundaryPolygon=null}const listener=map.addListener("click",e=>{if(!creatingFarm)return;newBoundary.push({lat:e.latLng.lat(),lng:e.latLng.lng()});renderDraftBoundary();});map.__farmDrawListener=listener;toast("Click each boundary corner. Use FINISH BOUNDARY when complete.")}
function renderDraftBoundary(){if(!map)return;if(boundaryPolygon)boundaryPolygon.setMap(null);boundaryPolygon=new google.maps.Polygon({paths:newBoundary,strokeColor:"#00b8d9",strokeOpacity:.95,strokeWeight:3,fillColor:"#00b8d9",fillOpacity:.12,map,clickable:false});$("mapStatus").textContent=`DRAWING MODE · ${newBoundary.length} boundary points`}
function finishBoundary(){if(!creatingFarm||newBoundary.length<3){toast("A farm boundary needs at least 3 points.");return}creatingFarm=false;if(map&&map.__farmDrawListener){google.maps.event.removeListener(map.__farmDrawListener);map.__farmDrawListener=null}map.setOptions({draggableCursor:null});$("farmCreateModal").classList.add("show");$("boundaryStatus").textContent=`Boundary captured · ${newBoundary.length} points · now define the farm contents.`;toast("Boundary captured")}
function clearBoundary(){newBoundary=[];if(boundaryPolygon){boundaryPolygon.setMap(null);boundaryPolygon=null}creatingFarm=false;if(map){if(map.__farmDrawListener){google.maps.event.removeListener(map.__farmDrawListener);map.__farmDrawListener=null}map.setOptions({draggableCursor:null})}$("boundaryStatus").textContent="No boundary created.";$("mapStatus").textContent="Satellite map active · farm records loaded"}
function closeCreateFarm(){clearBoundary();$("farmCreateModal").classList.remove("show")}
function centroid(points){let lat=0,lng=0;points.forEach(p=>{lat+=p.lat;lng+=p.lng});return{lat:lat/points.length,lng:lng/points.length}}
function saveFarm(){if(newBoundary.length<3){toast("Draw the farm boundary first.");return}const name=$("newFarmName").value.trim();if(!name){toast("Enter a farm name.");return}const center=centroid(newBoundary);const crops=$("newFarmCrops").value.split(",").map(x=>x.trim()).filter(Boolean);const farm={id:`farm-user-${Date.now()}`,name,owner:$("newFarmOwner").value.trim()||"Unknown",region:$("newFarmRegion").value.trim()||"Unassigned",status:$("newFarmStatus").value,drones:Number($("newFarmDrones").value)||0,tractors:Number($("newFarmTractors").value)||0,livestock:Number($("newFarmLivestock").value)||0,annualHarvest:$("newFarmHarvest").value.trim(),lastService:$("newFarmService").value.trim(),crops,center,boundary:newBoundary.map(p=>({lat:p.lat,lng:p.lng})),opportunityScore:0,source:"user-created",createdAt:new Date().toISOString(),infrastructure:{buildings:Number($("newFarmBuildings").value)||0}};farms.push(farm);addFarm(farm);selected=farm;boundaryPolygon=null;newBoundary=[];$("farmCreateModal").classList.remove("show");$("farmCard").classList.remove("show");creatingFarm=false;toast("Farm created in this session");selectFarm(farm,true);resetCreateForm();$("mapStatus").textContent=`Farm created · ${farm.name} · record ${farm.id}`}
function resetCreateForm(){["newFarmName","newFarmOwner","newFarmRegion","newFarmCrops","newFarmHarvest","newFarmService"].forEach(id=>$(id).value="");["newFarmTractors","newFarmDrones","newFarmLivestock"].forEach(id=>$(id).value="0");$("newFarmBuildings").value="1";$("newFarmStatus").value="Prospect"}
function createScene(f){if(!window.THREE){toast("3D library is still loading.");return}const host=$("farmScene");host.innerHTML="";scene=new THREE.Scene();scene.background=new THREE.Color(0xb8c5b2);camera=new THREE.PerspectiveCamera(42,Math.max(host.clientWidth,1)/Math.max(host.clientHeight,1),.1,1000);camera.position.set(16,14,18);camera.lookAt(0,0,0);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(host.clientWidth,host.clientHeight);renderer.shadowMap.enabled=true;host.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x66705e,2.2));const sun=new THREE.DirectionalLight(0xffffff,2.4);sun.position.set(8,18,10);sun.castShadow=true;scene.add(sun);const ground=new THREE.Mesh(new THREE.PlaneGeometry(34,26),new THREE.MeshStandardMaterial({color:0x788d65,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);const field=new THREE.Mesh(new THREE.PlaneGeometry(18,10),new THREE.MeshStandardMaterial({color:0x9cae55}));field.rotation.x=-Math.PI/2;field.position.y=.03;scene.add(field);addFarmBuildings(f);addFarmEquipment(f);const road=new THREE.Mesh(new THREE.BoxGeometry(34,.05,1.2),new THREE.MeshStandardMaterial({color:0x8d8170}));road.position.set(0,.05,5);scene.add(road);sceneFarm=new THREE.Group();scene.add(sceneFarm);sceneObjects.forEach(o=>sceneFarm.add(o));animateScene()}
function box(x,y,z,sx,sy,sz,c){const o=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),new THREE.MeshStandardMaterial({color:c}));o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;sceneObjects.push(o);return o}
function addFarmBuildings(f){box(-5,1,-2,4,2,3,0xd6d0c1);box(-5,2.5,-2,4.3,1,3.2,0x7a6755);box(2,.8,-3,3,1.6,2,0xd9d2be);box(2,2,-3,3.2,.5,2.2,0x6e6252);if((f.infrastructure?.buildings||4)>2)box(0,.7,-6,2.5,1.4,2,0xb8b0a0)}
function addFarmEquipment(f){for(let i=0;i<(f.tractors||0);i++){const x=-7+(i%3)*2.8,z=2+Math.floor(i/3)*2;box(x,.45,z,1.5,.8,1,0x40515a);box(x,.95,z,1,.3,.8,0x687b82)}for(let i=0;i<(f.drones||0);i++){const x=5+i*2.1;const d=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(.8,.22,.5),new THREE.MeshStandardMaterial({color:0x222a2d}));d.add(body);for(const [x1,z1] of [[.65,.65],[-.65,.65],[.65,-.65],[-.65,-.65]]){const arm=new THREE.Mesh(new THREE.BoxGeometry(.9,.08,.08),new THREE.MeshStandardMaterial({color:0x333b3e}));arm.position.set(x1/2,.05,z1/2);d.add(arm);const rotor=new THREE.Mesh(new THREE.CylinderGeometry(.18,.18,.05,16),new THREE.MeshStandardMaterial({color:0x15191b}));rotor.position.set(x1,.08,z1);d.add(rotor)}d.position.set(x,2.2,3);sceneObjects.push(d)}}
function animateScene(){if(!renderer)return;animationId=requestAnimationFrame(animateScene);if(sceneFarm)sceneFarm.rotation.y+=.0025;renderer.render(scene,camera)}
function open3D(){if(!selected){toast("Select a farm first.");return}$("sceneTitle").textContent=selected.name.toUpperCase();$("sceneMeta").textContent=`${selected.region} · ${selected.status}`;$("sceneSummary").textContent=`${selected.drones} drones · ${selected.tractors} tractors · ${(selected.crops||[]).length} crop types · ${selected.livestock??0} livestock`;$("farm3dModal").classList.add("show");sceneObjects=[];createScene(selected)}
function close3D(){cancelAnimationFrame(animationId);if(renderer){renderer.dispose();renderer=null}sceneObjects=[];sceneFarm=null;$("farmScene").innerHTML="";$("farm3dModal").classList.remove("show")}
$("nationalBtn").onclick=national;$("satelliteBtn").onclick=()=>{if(map)map.setMapTypeId("satellite");else toast("Add the Google Maps API key in config.js first.")};$("resetBtn").onclick=national;$("createFarmBtn").onclick=openCreateFarm;$("closeCreateFarm").onclick=closeCreateFarm;$("startBoundary").onclick=startBoundary;$("finishBoundary").onclick=finishBoundary;$("clearBoundary").onclick=clearBoundary;$("saveFarm").onclick=saveFarm;$("farm3d").onclick=open3D;$("close3d").onclick=close3D;$("close3dBottom").onclick=close3D;$("farm3dModal").onclick=e=>{if(e.target.id==="farm3dModal")close3D()};$("farmCreateModal").onclick=e=>{if(e.target.id==="farmCreateModal")closeCreateFarm()};$("aiAction").onclick=()=>{const f=farms.filter(x=>x.drones===0).sort((a,b)=>(b.opportunityScore??0)-(a.opportunityScore??0))[0];if(f)selectFarm(f)};document.querySelectorAll(".mission").forEach(m=>m.onclick=()=>toast(`Mission opened: ${m.querySelector("strong").textContent}`));document.querySelectorAll(".nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");toast(`${b.textContent.trim()} selected`)});window.addEventListener("resize",()=>{const host=$("farmScene");if(renderer&&host.clientWidth){camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)}});loadFarms();