const CONFIG=window.AG_WORLD_CONFIG||{};
let farms=[],map=null,selected=null,scene=null,renderer=null,camera=null,animationId=null,sceneFarm=null,sceneObjects=[];
let newBoundary=[],boundaryPolygon=null,creatingFarm=false,placingObjectType=null,draftObjects=[],objectMarkers=[];
const $=id=>document.getElementById(id);
const OBJECT_TYPES={
  'crop-field':{label:'Crop field',icon:'🌾'},dam:{label:'Dam / water',icon:'◉'},building:{label:'Building',icon:'⌂'},tractor:{label:'Tractor',icon:'▣'},drone:{label:'Company drone',icon:'✦'},'competitor-drone':{label:'Competitor drone',icon:'◇'},'livestock-area':{label:'Livestock area',icon:'♢'},irrigation:{label:'Irrigation',icon:'≈'}
};
const toast=m=>{const t=$("toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)};
function saveLocal(){localStorage.setItem('agworld-farms-v1',JSON.stringify(farms.map(cleanFarm)));}
function cleanFarm(f){const o={...f};delete o._polygon;delete o._marker;return o}
async function loadFarms(){try{const r=await fetch("data/farms.json");if(!r.ok)throw Error();const base=(await r.json()).farms||[];let stored=[];try{stored=JSON.parse(localStorage.getItem('agworld-farms-v1')||'[]')}catch(e){}const byId=new Map(base.map(f=>[f.id,f]));stored.forEach(f=>byId.set(f.id,f));farms=[...byId.values()];initMap()}catch(e){$("mapStatus").textContent="Farm data could not be loaded."}}
function initMap(){if(!CONFIG.GOOGLE_MAPS_API_KEY){$("mapStatus").textContent="Google satellite mapping is configured but inactive: add the API key in config.js.";return}const s=document.createElement("script");s.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(CONFIG.GOOGLE_MAPS_API_KEY)}&libraries=drawing&callback=agWorldMapReady`;s.async=true;s.defer=true;document.head.appendChild(s)}
window.agWorldMapReady=()=>{map=new google.maps.Map($("map"),{center:{lat:-29,lng:24},zoom:5,mapTypeId:"satellite",fullscreenControl:false,streetViewControl:false,mapTypeControl:false,gestureHandling:"greedy",tilt:0,rotateControl:false});map.addListener("zoom_changed",updateZoomStage);farms.forEach(addFarm);updateZoomStage();$("mapStatus").textContent=`Satellite map active · ${farms.length} farm records loaded`};
function addFarm(f){const p=new google.maps.Polygon({paths:f.boundary||[],strokeOpacity:.9,strokeWeight:2,fillOpacity:.16,map,clickable:true});p.addListener("click",()=>{if(!creatingFarm)selectFarm(f,true)});const m=new google.maps.Marker({position:f.center,map,title:f.name,label:{text:"AG",color:"#fff",fontSize:"9px",fontWeight:"700"}});m.addListener("click",()=>{if(!creatingFarm)selectFarm(f,true)});f._polygon=p;f._marker=m;renderFarmObjects(f)}
function renderFarmObjects(f){(f.objects||[]).forEach(o=>addObjectMarker(f,o));}
function objectPosition(o){if(o.position)return o.position;if(o.geometry?.coordinates)return{lng:o.geometry.coordinates[0],lat:o.geometry.coordinates[1]};return null}
function addObjectMarker(f,o){if(!map)return;const pos=objectPosition(o);if(!pos)return;const type=OBJECT_TYPES[o.type]||{label:o.type||'Object',icon:'•'};const marker=new google.maps.Marker({position:pos,map,title:`${type.label}${o.name?` · ${o.name}`:''}`,label:{text:type.icon,color:'#ffffff',fontSize:'13px'}});marker.addListener('click',e=>{if(e.stop) e.stop();showObject(o,f)});objectMarkers.push(marker);o._marker=marker}
function clearDraftMarkers(){objectMarkers.forEach(m=>m.setMap(null));objectMarkers=[];farms.forEach(f=>{if(f._marker)f._marker.setMap(map);if(f._polygon)f._polygon.setMap(map)});if(selected)renderFarmObjects(selected)}
function showObject(o,f){const type=OBJECT_TYPES[o.type]||{label:o.type,icon:'•'};$("farmCard").classList.add("show");$("farmName").textContent=o.name||type.label;$("farmMeta").textContent=`${f.name} · ${type.label} · ${o.source||'manual'}`;$("farmDetailText").textContent=Object.entries(o.properties||{}).map(([k,v])=>`${k}: ${v}`).join(" · ")||`Positioned object on ${f.name}.`;$("farmDrones").textContent=o.type==='drone'?1:f.drones||0;$("farmTractors").textContent=o.type==='tractor'?1:f.tractors||0;$("farmCrops").textContent=o.type==='crop-field'?1:(f.crops||[]).length;$("farmScore").textContent=f.opportunityScore??"—";$("farmLivestock").textContent=o.type==='livestock-area'?'AREA':f.livestock??"—";$("farmHarvest").textContent=f.annualHarvest??"—";$("farmService").textContent=f.lastService??"—"}
function updateZoomStage(){if(!map)return;const z=map.getZoom();let stage=z<7?1:z<9?2:z<12?3:4;$("zoomStage").textContent=`ZOOM ${stage} · ${["NATIONAL OVERVIEW","REGIONAL FARMS","FARM BOUNDARY","INTERACTIVE FARM"][stage-1]}`;if(stage>=3&&selected)showFarmDetail(selected)}
function selectFarm(f,zoom=true){if(creatingFarm)return;selected=f;$("farmCard").classList.add("show");$("farmName").textContent=f.name;$("farmMeta").textContent=`${f.region} · ${f.status} · ${f.owner}`;$("farmDrones").textContent=f.drones||0;$("farmTractors").textContent=f.tractors||0;$("farmCrops").textContent=(f.crops||[]).length;$("farmScore").textContent=f.opportunityScore??"—";$("farmLivestock").textContent=f.livestock??"—";$("farmHarvest").textContent=f.annualHarvest??"—";$("farmService").textContent=f.lastService??"—";const objects=(f.objects||[]).map(o=>(OBJECT_TYPES[o.type]?.label||o.type)).join(', ');$("farmDetailText").textContent=`Crops: ${(f.crops||[]).join(", ")||"Not recorded"}. ${objects?`Mapped objects: ${objects}. ` : ''}${f.drones?`${f.drones} company drone asset${f.drones===1?"":"s"} recorded.`:"No company drone recorded — commercial opportunity."}`;$("aiText").textContent=f.drones===0?`${f.name} has no company drone recorded and scores ${f.opportunityScore??"—"}/100. Qualify this opportunity and move the territory forward.`:`${f.name} is an active relationship. Protect the account through service quality and customer satisfaction.`;if(map&&zoom){map.panTo(f.center);map.setZoom(12)}showFarmDetail(f)}
function showFarmDetail(f){if(map&&map.getZoom()>=9)$("mapStatus").textContent=`Farm selected · ${f.name} · boundary and ${f.objects?.length||0} mapped objects linked to record ${f.id}`}
function national(){if(map){map.setCenter({lat:-29,lng:24});map.setZoom(5);$("farmCard").classList.remove("show");selected=null}}
function openCreateFarm(){if(!map){toast("Add the Google Maps API key first.");return}creatingFarm=true;newBoundary=[];draftObjects=[];placingObjectType=null;clearDraftMarkers();if(boundaryPolygon){boundaryPolygon.setMap(null);boundaryPolygon=null}renderObjectEditor();$("farmCreateModal").classList.add("show");$("boundaryStatus").textContent="Click START BOUNDARY, then draw the farm polygon on the satellite map.";$("objectStatus").textContent="Draw a boundary first, then choose an object type.";toast("Create Farm mode ready")}
function startBoundary(){if(!map)return;creatingFarm=true;placingObjectType=null;$("farmCreateModal").classList.remove("show");$("mapStatus").textContent="DRAWING MODE · click the farm boundary points on the satellite map";map.setOptions({draggableCursor:"crosshair"});newBoundary=[];draftObjects=[];if(boundaryPolygon){boundaryPolygon.setMap(null);boundaryPolygon=null}clearDraftMarkers();if(map.__farmDrawListener)google.maps.event.removeListener(map.__farmDrawListener);map.__farmDrawListener=map.addListener("click",e=>{if(!creatingFarm||placingObjectType)return;if(placingObjectType){placeObject(e.latLng);return}newBoundary.push({lat:e.latLng.lat(),lng:e.latLng.lng()});renderDraftBoundary()});toast("Click each boundary corner")}
function renderDraftBoundary(){if(!map)return;if(boundaryPolygon)boundaryPolygon.setMap(null);boundaryPolygon=new google.maps.Polygon({paths:newBoundary,strokeColor:"#00b8d9",strokeOpacity:.95,strokeWeight:3,fillColor:"#00b8d9",fillOpacity:.12,map,clickable:false});$("mapStatus").textContent=`DRAWING MODE · ${newBoundary.length} boundary points`}
function finishBoundary(){if(!creatingFarm||newBoundary.length<3){toast("A farm boundary needs at least 3 points.");return}if(map&&map.__farmDrawListener){google.maps.event.removeListener(map.__farmDrawListener);map.__farmDrawListener=null}map.setOptions({draggableCursor:null});creatingFarm=false;$("farmCreateModal").classList.add("show");$("boundaryStatus").textContent=`Boundary captured · ${newBoundary.length} points`;$("objectStatus").textContent="Choose an object type, then click its position on the map.";renderObjectEditor();toast("Boundary captured")}
function clearBoundary(){newBoundary=[];draftObjects=[];placingObjectType=null;if(boundaryPolygon){boundaryPolygon.setMap(null);boundaryPolygon=null}if(map){if(map.__farmDrawListener)google.maps.event.removeListener(map.__farmDrawListener);map.__farmDrawListener=null;map.setOptions({draggableCursor:null})}clearDraftMarkers();$("boundaryStatus").textContent="No boundary created.";$("objectStatus").textContent="No object selected.";renderObjectEditor();$("mapStatus").textContent="Satellite map active · farm records loaded"}
function closeCreateFarm(){clearBoundary();$("farmCreateModal").classList.remove("show")}
function centroid(points){let lat=0,lng=0;points.forEach(p=>{lat+=p.lat;lng+=p.lng});return{lat:lat/points.length,lng:lng/points.length}}
function pointInside(point,poly){if(!poly||poly.length<3)return false;let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const xi=poly[i].lat,yi=poly[i].lng,xj=poly[j].lat,yj=poly[j].lng;const intersect=((yi>point.lng)!=(yj>point.lng))&&(point.lat<(xj-xi)*(point.lng-yi)/(yj-yi)+xi);if(intersect)inside=!inside}return inside}
function chooseObject(type){if(newBoundary.length<3){toast("Draw and finish the farm boundary first.");return}placingObjectType=type;creatingFarm=true;document.querySelectorAll('.object-palette button').forEach(b=>b.classList.toggle('active',b.dataset.object===type));$("farmCreateModal").classList.remove("show");map.setOptions({draggableCursor:"crosshair"});$("mapStatus").textContent=`PLACE MODE · click inside boundary to place ${OBJECT_TYPES[type].label}`;if(map.__farmDrawListener)google.maps.event.removeListener(map.__farmDrawListener);map.__farmDrawListener=map.addListener('click',e=>placeObject(e.latLng));toast(`Place ${OBJECT_TYPES[type].label} on the farm`)}
function placeObject(latLng){if(!placingObjectType)return;const position={lat:latLng.lat(),lng:latLng.lng()};if(!pointInside(position,newBoundary)){toast("Object must be placed inside the farm boundary.");return}const type=placingObjectType;const obj={id:`obj-${Date.now()}-${draftObjects.length}`,type,name:OBJECT_TYPES[type].label,position,source:'manual',createdAt:new Date().toISOString(),properties:{}};draftObjects.push(obj);const marker=new google.maps.Marker({position,map,title:obj.name,label:{text:OBJECT_TYPES[type].icon,color:'#fff',fontSize:'13px'}});marker.addListener('click',()=>toast(`${obj.name} · ${position.lat.toFixed(5)}, ${position.lng.toFixed(5)}`));objectMarkers.push(marker);renderObjectEditor();$("farmCreateModal").classList.add("show");placingObjectType=null;creatingFarm=false;if(map.__farmDrawListener)google.maps.event.removeListener(map.__farmDrawListener);map.__farmDrawListener=null;map.setOptions({draggableCursor:null});$("objectStatus").textContent=`${obj.name} placed. Choose another object to continue.`;$("mapStatus").textContent=`Object placed · ${obj.name} · ${draftObjects.length} farm objects`}
function removeDraftObject(id){draftObjects=draftObjects.filter(o=>o.id!==id);clearDraftMarkers();if(boundaryPolygon)boundaryPolygon.setMap(map);draftObjects.forEach(o=>{const marker=new google.maps.Marker({position:o.position,map,title:o.name,label:{text:OBJECT_TYPES[o.type].icon,color:'#fff',fontSize:'13px'}});objectMarkers.push(marker)});renderObjectEditor()}
function renderObjectEditor(){const list=$("objectList"),summary=$("objectSummary");if(!list)return;list.innerHTML=draftObjects.map(o=>`<div class="object-row"><span>${OBJECT_TYPES[o.type]?.icon||'•'} ${o.name}</span><button data-remove="${o.id}">REMOVE</button></div>`).join('');list.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>removeDraftObject(b.dataset.remove));const counts={};draftObjects.forEach(o=>counts[o.type]=(counts[o.type]||0)+1);summary.textContent=draftObjects.length?Object.entries(counts).map(([t,n])=>`${n} × ${OBJECT_TYPES[t].label}`).join(' · '):'No objects placed yet.'}
function saveFarm(){if(newBoundary.length<3){toast("Draw the farm boundary first.");return}const name=$("newFarmName").value.trim();if(!name){toast("Enter a farm name.");return}const center=centroid(newBoundary);const objects=draftObjects.map(o=>({...o,properties:{...o.properties}}));const cropNames=objects.filter(o=>o.type==='crop-field').map(o=>o.name);const droneCount=objects.filter(o=>o.type==='drone').length;const tractorCount=objects.filter(o=>o.type==='tractor').length;const livestockCount=objects.filter(o=>o.type==='livestock-area').length;const farm={id:`farm-user-${Date.now()}`,name,owner:$("newFarmOwner").value.trim()||"Unknown",region:$("newFarmRegion").value.trim()||"Unassigned",status:$("newFarmStatus").value,drones:droneCount,tractors:tractorCount,livestock:livestockCount,annualHarvest:$("newFarmHarvest").value.trim(),lastService:$("newFarmService").value.trim(),crops:cropNames,center,boundary:newBoundary.map(p=>({lat:p.lat,lng:p.lng})),objects,opportunityScore:0,source:"manual",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),notes:$("newFarmNotes").value.trim(),audit:[{action:'created',source:'manual',at:new Date().toISOString()}]};farms.push(farm);saveLocal();if(boundaryPolygon)boundaryPolygon.setMap(null);objectMarkers.forEach(m=>m.setMap(null));objectMarkers=[];addFarm(farm);selected=farm;newBoundary=[];draftObjects=[];boundaryPolygon=null;creatingFarm=false;placingObjectType=null;$("farmCreateModal").classList.remove("show");$("farmCard").classList.remove("show");toast("Farm record saved locally");selectFarm(farm,true);resetCreateForm();$("mapStatus").textContent=`Farm saved · ${farm.name} · ${farm.objects.length} mapped objects · local dataset updated`}
function resetCreateForm(){["newFarmName","newFarmOwner","newFarmRegion","newFarmHarvest","newFarmService","newFarmNotes"].forEach(id=>$(id).value="");$("newFarmStatus").value="Prospect";draftObjects=[];renderObjectEditor()}
function exportData(){const blob=new Blob([JSON.stringify({farms:farms.map(cleanFarm)},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ag-world-farms.json';a.click();URL.revokeObjectURL(a.href);toast('Farm dataset exported')}
function importData(){if(!map){toast('Add the Google Maps API key first.');return}$("datasetFile").click()}
async function handleImport(e){const file=e.target.files?.[0];if(!file)return;try{const text=await file.text();let data=JSON.parse(text);let incoming=[];if(Array.isArray(data))incoming=data;else if(Array.isArray(data.farms))incoming=data.farms;else if(data.type==='FeatureCollection')incoming=geoJsonToFarms(data);else throw Error('Unsupported JSON structure');incoming=incoming.map(normalizeImportedFarm).filter(Boolean);const byId=new Map(farms.map(f=>[f.id,f]));incoming.forEach(f=>byId.set(f.id,f));farms=[...byId.values()];saveLocal();farms.forEach(f=>{if(!f._marker)addFarm(f)});$("mapStatus").textContent=`Dataset imported · ${incoming.length} farm records`;toast(`${incoming.length} farm records imported`)}catch(err){toast('Import failed: use AG World farm JSON or GeoJSON.')}e.target.value=''}
function geoJsonToFarms(fc){return fc.features.map((feature,i)=>{const g=feature.geometry,p=feature.properties||{};if(!g)return null;let boundary=null,center=null;if(g.type==='Polygon'){const ring=g.coordinates?.[0]||[];boundary=ring.map(c=>({lat:c[1],lng:c[0]}));center=centroid(boundary)}else if(g.type==='Point'){center={lat:g.coordinates[1],lng:g.coordinates[0]};boundary=[{lat:center.lat-.01,lng:center.lng-.01},{lat:center.lat-.01,lng:center.lng+.01},{lat:center.lat+.01,lng:center.lng+.01},{lat:center.lat+.01,lng:center.lng-.01}]}return boundary?{id:p.id||`import-${Date.now()}-${i}`,name:p.name||p.farm_name||`Imported Farm ${i+1}`,owner:p.owner||p.farmer||'Unknown',region:p.region||p.province||'Imported',status:p.status||'Prospect',drones:Number(p.drones)||0,tractors:Number(p.tractors)||0,livestock:Number(p.livestock)||0,crops:Array.isArray(p.crops)?p.crops:typeof p.crops==='string'?p.crops.split(',').map(x=>x.trim()).filter(Boolean):[],annualHarvest:p.annualHarvest||'',lastService:p.lastService||'',opportunityScore:Number(p.opportunityScore)||0,center,boundary,objects:Array.isArray(p.objects)?p.objects:[],source:'import',updatedAt:new Date().toISOString()}:null})}
function normalizeImportedFarm(f){if(!f||!f.boundary)return null;const boundary=f.boundary.map(p=>({lat:Number(p.lat),lng:Number(p.lng)}));return {...f,id:f.id||`import-${Date.now()}-${Math.random()}`,center:f.center||centroid(boundary),objects:Array.isArray(f.objects)?f.objects:[],source:'import',updatedAt:new Date().toISOString()}}
function createScene(f){if(!window.THREE){toast("3D library is still loading.");return}const host=$("farmScene");host.innerHTML="";scene=new THREE.Scene();scene.background=new THREE.Color(0xb8c5b2);camera=new THREE.PerspectiveCamera(42,Math.max(host.clientWidth,1)/Math.max(host.clientHeight,1),.1,1000);camera.position.set(16,14,18);camera.lookAt(0,0,0);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(host.clientWidth,host.clientHeight);renderer.shadowMap.enabled=true;host.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x66705e,2.2));const sun=new THREE.DirectionalLight(0xffffff,2.4);sun.position.set(8,18,10);sun.castShadow=true;scene.add(sun);const ground=new THREE.Mesh(new THREE.PlaneGeometry(34,26),new THREE.MeshStandardMaterial({color:0x788d65,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);const field=new THREE.Mesh(new THREE.PlaneGeometry(18,10),new THREE.MeshStandardMaterial({color:0x9cae55}));field.rotation.x=-Math.PI/2;field.position.y=.03;scene.add(field);addFarmBuildings(f);addFarmEquipment(f);const road=new THREE.Mesh(new THREE.BoxGeometry(34,.05,1.2),new THREE.MeshStandardMaterial({color:0x8d8170}));road.position.set(0,.05,5);scene.add(road);sceneFarm=new THREE.Group();scene.add(sceneFarm);sceneObjects.forEach(o=>sceneFarm.add(o));animateScene()}
function box(x,y,z,sx,sy,sz,c){const o=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),new THREE.MeshStandardMaterial({color:c}));o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;sceneObjects.push(o);return o}
function addFarmBuildings(f){const buildings=(f.objects||[]).filter(o=>o.type==='building').length||1;for(let i=0;i<buildings;i++){const x=-5+(i%2)*7,z=-2+Math.floor(i/2)*4;box(x,1,z,4,2,3,0xd6d0c1);box(x,2.5,z,4.3,1,3.2,0x7a6755)}}
function addFarmEquipment(f){const tractors=(f.objects||[]).filter(o=>o.type==='tractor').length||f.tractors||0;for(let i=0;i<tractors;i++){const x=-7+(i%3)*2.8,z=2+Math.floor(i/3)*2;box(x,.45,z,1.5,.8,1,0x40515a);box(x,.95,z,1,.3,.8,0x687b82)}const drones=(f.objects||[]).filter(o=>o.type==='drone').length||f.drones||0;for(let i=0;i<drones;i++){const x=5+i*2.1;const d=new THREE.Group();d.add(new THREE.Mesh(new THREE.BoxGeometry(.8,.22,.5),new THREE.MeshStandardMaterial({color:0x222a2d})));d.position.set(x,2.2,3);sceneObjects.push(d)}const dams=(f.objects||[]).filter(o=>o.type==='dam').length;for(let i=0;i<dams;i++){const water=new THREE.Mesh(new THREE.CylinderGeometry(2.3,2.3,.12,32),new THREE.MeshStandardMaterial({color:0x447d91,roughness:.3}));water.rotation.x=0;water.position.set(-4+i*5,.08,-7);sceneObjects.push(water)}}
function animateScene(){if(!renderer)return;animationId=requestAnimationFrame(animateScene);if(sceneFarm)sceneFarm.rotation.y+=.0025;renderer.render(scene,camera)}
function open3D(){if(!selected){toast("Select a farm first.");return}$("sceneTitle").textContent=selected.name.toUpperCase();$("sceneMeta").textContent=`${selected.region} · ${selected.status}`;$("sceneSummary").textContent=`${selected.drones||0} drones · ${selected.tractors||0} tractors · ${(selected.objects||[]).length} mapped objects · ${(selected.crops||[]).length} crop types`;$("farm3dModal").classList.add("show");sceneObjects=[];createScene(selected)}
function close3D(){cancelAnimationFrame(animationId);if(renderer){renderer.dispose();renderer=null}sceneObjects=[];sceneFarm=null;$("farmScene").innerHTML="";$("farm3dModal").classList.remove("show")}
$("nationalBtn").onclick=national;$("satelliteBtn").onclick=()=>{if(map)map.setMapTypeId("satellite");else toast("Add the Google Maps API key in config.js first.")};$("resetBtn").onclick=national;$("createFarmBtn").onclick=openCreateFarm;$("closeCreateFarm").onclick=closeCreateFarm;$("startBoundary").onclick=startBoundary;$("finishBoundary").onclick=finishBoundary;$("clearBoundary").onclick=clearBoundary;$("saveFarm").onclick=saveFarm;$("importBtn").onclick=importData;$("exportBtn").onclick=exportData;$("datasetFile").onchange=handleImport;document.querySelectorAll('.object-palette button').forEach(b=>b.onclick=()=>chooseObject(b.dataset.object));$("farm3d").onclick=open3D;$("close3d").onclick=close3D;$("close3dBottom").onclick=close3D;$("farm3dModal").onclick=e=>{if(e.target.id==="farm3dModal")close3D()};$("farmCreateModal").onclick=e=>{if(e.target.id==="farmCreateModal")closeCreateFarm()};$("aiAction").onclick=()=>{const f=farms.filter(x=>(x.drones||0)===0).sort((a,b)=>(b.opportunityScore??0)-(a.opportunityScore??0))[0];if(f)selectFarm(f)};document.querySelectorAll(".mission").forEach(m=>m.onclick=()=>toast(`Mission opened: ${m.querySelector("strong").textContent}`));document.querySelectorAll(".nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");toast(`${b.textContent.trim()} selected`)});window.addEventListener("resize",()=>{const host=$("farmScene");if(renderer&&host.clientWidth){camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)}});loadFarms();