const CONFIG=window.AG_WORLD_CONFIG||{};let farms=[];let map=null;let selected=null;const markers=[];const polygons=[];let scene,renderer,camera,animationId,sceneFarm;
const $=id=>document.getElementById(id);const toast=m=>{const t=$("toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)};
async function loadFarms(){try{const r=await fetch("data/farms.json");farms=(await r.json()).farms;initMap()}catch(e){$("mapStatus").textContent="Farm data could not be loaded."}}
function initMap(){if(!CONFIG.GOOGLE_MAPS_API_KEY){$("mapStatus").textContent="Google Maps is ready — add your API key in config.js to activate satellite mapping.";return}const s=document.createElement("script");s.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(CONFIG.GOOGLE_MAPS_API_KEY)}&callback=agWorldMapReady`;s.async=true;s.defer=true;document.head.appendChild(s)}
window.agWorldMapReady=()=>{map=new google.maps.Map($("map"),{center:{lat:-29.0,lng:24.0},zoom:5,mapTypeId:"satellite",fullscreenControl:false,streetViewControl:false,mapTypeControl:false,gestureHandling:"greedy"});$("mapStatus").textContent="Satellite map active · demonstration farm records loaded";farms.forEach(addFarm);};
function addFarm(f){const p=new google.maps.Polygon({paths:f.boundary,strokeOpacity:.9,strokeWeight:2,fillOpacity:.16,map});p.addListener("click",()=>selectFarm(f));polygons.push(p);const m=new google.maps.Marker({position:f.center,map,title:f.name,label:{text:"AG",color:"#ffffff",fontSize:"9px",fontWeight:"700"}});m.addListener("click",()=>selectFarm(f));markers.push(m)}
function selectFarm(f){selected=f;$("farmCard").classList.add("show");$("farmName").textContent=f.name;$("farmMeta").textContent=`${f.region} · ${f.status} · ${f.owner}`;$("farmDrones").textContent=f.drones;$("farmTractors").textContent=f.tractors;$("farmCrops").textContent=f.crops.length;$("farmScore").textContent=f.opportunityScore;$("aiText").textContent=f.drones===0?`${f.name} has no company drone recorded and scores ${f.opportunityScore}/100. Qualify this opportunity and move the territory forward.`:`${f.name} is an active relationship. Protect the account through service quality and customer satisfaction.`;if(map)map.panTo(f.center)}
function national(){if(map){map.setCenter({lat:-29,lng:24});map.setZoom(5)}}
function createScene(f){const host=$("farmScene");host.innerHTML="";scene=new THREE.Scene();scene.background=new THREE.Color(0xb8c5b2);camera=new THREE.PerspectiveCamera(42,host.clientWidth/host.clientHeight,.1,1000);camera.position.set(16,15,18);camera.lookAt(0,0,0);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.setSize(host.clientWidth,host.clientHeight);renderer.shadowMap.enabled=true;host.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x66705e,2.2));const sun=new THREE.DirectionalLight(0xffffff,2.5);sun.position.set(10,20,8);sun.castShadow=true;scene.add(sun);const ground=new THREE.Mesh(new THREE.PlaneGeometry(30,24),new THREE.MeshStandardMaterial({color:0x788d65,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);const field=new THREE.Mesh(new THREE.PlaneGeometry(18,10),new THREE.MeshStandardMaterial({color:0x9cae55}));field.rotation.x=-Math.PI/2;field.position.y=.02;scene.add(field);addFarmBuildings(f);addEquipment(f);const roads=new THREE.Mesh(new THREE.BoxGeometry(30,.05,1.2),new THREE.MeshStandardMaterial({color:0x8d8170}));roads.position.set(0,.04,4);scene.add(roads);animateScene()}
function box(x,y,z,sx,sy,sz,c){const o=new THREE.Mesh(new THREE.BoxGeometry(sx,sy,sz),new THREE.MeshStandardMaterial({color:c}));o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;scene.add(o);return o}
function addFarmBuildings(f){box(-5,1,-2,4,2,3,0xd6d0c1);box(-5,2.5,-2,4.3,1,3.2,0x7a6755);box(2,.8,-3,3,1.6,2,0xd9d2be);box(2,2,-3,3.2,.5,2.2,0x6e6252);for(let i=0;i<4;i++)box(-5.7+i*.42,1.0,-3.53,.24,1.1,.08,0x526a78)}
function addEquipment(f){for(let i=0;i<f.tractors;i++){const x=-7+(i%3)*2.8,z=2+Math.floor(i/3)*2;box(x,.45,z,1.5,.8,1,0x40515a);box(x,.95,z,1,.3,.8,0x687b82)}for(let i=0;i<f.drones;i++){const x=5+i*2.1;const d=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(.8,.22,.5),new THREE.MeshStandardMaterial({color:0x222a2d}));d.add(body);for(const p of [[.65,.05,.65],[-.65,.05,.65],[.65,.05,-.65],[-.65,.05,-.65]]){const arm=new THREE.Mesh(new THREE.BoxGeometry(.9,.08,.08),new THREE.MeshStandardMaterial({color:0x333b3e}));arm.position.set(p[0]/2,.05,p[2]/2);d.add(arm);const rotor=new THREE.Mesh(new THREE.CylinderGeometry(.18,.18,.05,16),new THREE.MeshStandardMaterial({color:0x15191b}));rotor.position.set(p[0],.08,p[2]);d.add(rotor)}d.position.set(x,2.2,3);scene.add(d)}}
function animateScene(){if(!renderer)return;animationId=requestAnimationFrame(animateScene);if(sceneFarm){sceneFarm.rotation.y+=.003}renderer.render(scene,camera)}
function open3D(){if(!selected){toast("Select a farm first.");return}$("sceneTitle").textContent=selected.name.toUpperCase();$("sceneMeta").textContent=`${selected.region} · ${selected.status}`;$("sceneSummary").textContent=`${selected.drones} drones · ${selected.tractors} tractors · ${selected.crops.length} crop types`;$("farm3dModal").classList.add("show");createScene(selected)}
function close3D(){cancelAnimationFrame(animationId);if(renderer){renderer.dispose();renderer=null}$("farmScene").innerHTML="";$("farm3dModal").classList.remove("show")}
$("nationalBtn").onclick=national;$("satelliteBtn").onclick=()=>{if(map)map.setMapTypeId("satellite");else toast("Add the Google Maps API key in config.js first.")};$("resetBtn").onclick=()=>{national();$("farmCard").classList.remove("show")};$("farm3d").onclick=open3D;$("close3d").onclick=close3D;$("close3dBottom").onclick=close3D;$("farm3dModal").onclick=e=>{if(e.target.id==="farm3dModal")close3D()};$("aiAction").onclick=()=>{const f=farms.filter(x=>x.drones===0).sort((a,b)=>b.opportunityScore-a.opportunityScore)[0];if(f)selectFarm(f)};document.querySelectorAll(".mission").forEach(m=>m.onclick=()=>toast(`Mission opened: ${m.querySelector("strong").textContent}`));document.querySelectorAll(".nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");toast(`${b.textContent.trim()} selected`)});window.addEventListener("resize",()=>{const host=$("farmScene");if(renderer&&host.clientWidth){camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)}});loadFarms();