(()=>{const $=id=>document.getElementById(id);let auto=true,errors=[];const opener=()=>{try{return window.opener&&!window.opener.closed?window.opener:null}catch(e){return null}};const root=()=>opener()||window;
function value(fn,fallback='Unavailable'){try{const v=fn();return v??fallback}catch(e){return fallback}}
function getWorld(w){return w.AG_WORLD_WORLD||{}}
function entityCounts(w){const world=getWorld(w);const farms=Array.isArray(world.farms)?world.farms.length:0;const contractors=value(()=>world.getContractors().length,0);const competitors=value(()=>world.getCompetitors().length,0);const facilities=value(()=>world.getCompanyFacilities().length,0);return {farms,contractors,competitors,facilities,total:farms+contractors+competitors+facilities}}
function relationshipData(w){const s=w.marketInfluenceState||w.relationshipState||w.relationshipNetworkState||{};const candidates=[s.relationships,w.relationships,w.AG_WORLD_RELATIONSHIPS];for(const x of candidates)if(Array.isArray(x))return x;return []}
function eventData(w){const e=w.worldEventState||w.worldEventsState||w.AG_WORLD_WORLD_EVENTS||{};if(Array.isArray(e))return e;if(Array.isArray(e.events))return e.events;return []}
function yes(v){return v===true||!!v}
function diag(){const w=root(),world=getWorld(w),counts=entityCounts(w),rels=relationshipData(w),events=eventData(w),map=w.document&&w.document.getElementById('map');const checks=[
{name:'APPLICATION & RUNTIME',state:yes(w.AG_WORLD_WORLD)?'pass':'warn',items:[['Main world API',!!w.AG_WORLD_WORLD],['Map element',!!map],['Leaflet available',!!w.L],['Entity V2 host',!!(w.document&&w.document.getElementById('agworldV2FarmDetailHost'))]]},
{name:'GIS & MAP',state:map?'pass':'fail',items:[['Map element present',!!map],['Map has child layers',map?map.children.length:'No map'],['Map status',value(()=>w.document.getElementById('mapStatus').textContent,'Unavailable')],['Map object exposed',!!w.map]]},
(()=>{const doc=w.document;const staleAssets=['live-profile-footer.css','footer-layout-fix.css','footer-final-layout.css','footer-background-fix.css','live-profile-footer.js','footer-final-layout.js'];const loaded=[...(doc?.querySelectorAll('link[href],script[src]')||[])].map(el=>el.getAttribute('href')||el.getAttribute('src')||'');const active=staleAssets.filter(name=>loaded.some(src=>src.includes(name)));const layoutLocked=!!w.__AGWORLD_MAIN_LAYOUT_LOCKED__;const oldFooter=doc?.querySelector('.bottom.user-profile-section');const visibleOldFooter=!!oldFooter&&w.getComputedStyle(oldFooter).display!=='none'&&w.getComputedStyle(oldFooter).visibility!=='hidden';const panels=!!(doc?.getElementById('territorySection')&&doc?.getElementById('entityInformationSection'));const state=(active.length===0&&layoutLocked&&!visibleOldFooter&&panels)?'pass':'warn';return {name:'LAYOUT OWNERSHIP & STALE LAYERS',state,items:[['Main layout lock',layoutLocked],['Legacy footer assets active',active.length?active.join(', '):'NONE'],['Old profile footer visible',visibleOldFooter],['Fixed territory section',!!doc?.getElementById('territorySection')],['Fixed entity section',!!doc?.getElementById('entityInformationSection')],['Layout panel split',panels?'READY':'MISSING']]}})(),(()=>{const q=id=>w.document.getElementById(id);const rect=el=>el?el.getBoundingClientRect():null;const t=rect(q('territorySection')),e=rect(q('entityInformationSection')),m=rect(w.document?.querySelector?.('.map-area')||null);const aligned=!!t&&!!e&&Math.abs(t.top-e.top)<2&&Math.abs(t.height-e.height)<2;const stacked=!!m&&!!e&&Math.abs(m.bottom-e.top)<2;return {name:'MAIN SCREEN GEOMETRY',state:(aligned&&stacked)?'pass':'fail',items:[['Territory/entity top aligned',aligned],['Territory/entity equal height',!!t&&!!e&&Math.abs(t.height-e.height)<2],['Map directly above entity',stacked],['Geometry',w.__AGWORLD_MAIN_LAYOUT_GEOMETRY__?JSON.stringify(w.__AGWORLD_MAIN_LAYOUT_GEOMETRY__):'Unavailable']]}})(),
{name:'ENTITY POPULATION',state:counts.total?'pass':'warn',items:[['Farms',counts.farms],['Contractors',counts.contractors],['Competitors',counts.competitors],['Company Facilities',counts.facilities],['TOTAL',counts.total]]},
{name:'RELATIONSHIP ENGINE',state:rels.length?'pass':'warn',items:[['Relationship records',rels.length],['Relationship API',!!(w.EntityRelationshipEngine||w.relationshipEngine||w.marketInfluenceState)],['Network state',!!w.relationshipNetworkState],['Rule: unique farm contractor',value(()=>w.marketInfluenceState?.uniqueFarmContractorRule,'Check manually')]]},
{name:'TERRITORY & MARKET INFLUENCE',state:(w.marketInfluenceState||w.territoryControlState)?'pass':'warn',items:[['Market influence state',!!w.marketInfluenceState],['Territory control state',!!w.territoryControlState],['Territory panel',!!(w.document&&w.document.getElementById('territoryInfoPanel'))],['Drone-weighted influence API',!!w.dronePortfolioInfluence]]},
{name:'WORLD EVENTS',state:(w.WorldEventConsequenceEngine||w.worldEventState||events.length)?'pass':'warn',items:[['Event engine',!!(w.WorldEventConsequenceEngine||w.worldEventConsequenceEngine)],['Management UI',!!w.document?.getElementById('worldEventsNavBtn')],['Event records',events.length],['Active event state',!!w.worldEventState]]},
(()=>{const fleetHealth=typeof w.AGWorldFleetUI?.health==='function'?w.AGWorldFleetUI.health({repair:true}):null;const core=!!(w.openFleetTransaction&&w.openFleetManagement&&w.AGWorldFleetUI);const selected=!!fleetHealth?.eligible;const state=core&&(!selected||fleetHealth?.healthy)?'pass':'warn';return {name:'SALES & FLEET',state,items:[['Sell / Manage function',!!w.openFleetTransaction],['Fleet management function',!!w.openFleetManagement],['Fleet public bridge',!!w.AGWorldFleetUI],['Transaction modal',!!w.document?.getElementById('fleetTransactionModal')],['Fleet history modal',!!w.document?.getElementById('fleetManagementModal')],['Selected eligible entity',selected?'READY':'NOT SELECTED'],['Fleet action host',selected?(fleetHealth?.host??false):'NOT TESTED'],['Live quick-action host',selected?(fleetHealth?.quickActions??false):'NOT TESTED'],['Sell button visible',selected?(fleetHealth?.sellVisible??false):'NOT TESTED'],['History button visible',selected?(fleetHealth?.historyVisible??false):'NOT TESTED'],['Fleet UI health',selected?(fleetHealth?.healthy??false):'NOT TESTED']]}})(),
{name:'DEMO & WORLD POPULATION',state:(w.AG_WORLD_WORLD||w.WorldPopulationManager)?'pass':'warn',items:[['Population manager',!!(w.WorldPopulationManager||w.worldPopulationManager)],['Demo baseline',!!w.worldPopulationState],['Company facilities seeded',counts.facilities],['Contractors seeded',counts.contractors]]},
{name:'PERSISTENCE & BACKEND',state:(w.supabase||w.AG_WORLD_API_BASE||w.localStorage)?'pass':'warn',items:[['Supabase client',!!w.supabase],['API base',w.AG_WORLD_API_BASE||'Not exposed'],['Local storage',!!w.localStorage],['Shared backend bridge',!!(w.AG_WORLD_BACKEND||w.sharedBackend)]]},
(()=>{const doc=w.document;const q=s=>doc?.querySelector(s);const rect=el=>el?el.getBoundingClientRect():null;const shell=q('.app-shell'),side=q('.sidebar'),missions=q('.missions'),mapArea=q('.map-area'),territory=q('#territorySection'),entity=q('#entityInformationSection'),panel=q('#territoryInfoPanel'),card=q('#farmCard');const sr=rect(side),mr=rect(missions),mapr=rect(mapArea),tr=rect(territory),er=rect(entity);const leftOrder=!!sr&&!!mr&&Math.abs(sr.right-mr.left)<3;const topOrder=!!mr&&!!mapr&&Math.abs(mr.right-mapr.left)<3;const bottomAligned=!!tr&&!!er&&Math.abs(tr.top-er.top)<3&&Math.abs(tr.height-er.height)<3;const territoryUnderLeft=!!tr&&!!mapr&&Math.abs(tr.top-mapr.bottom)<3;const entityUnderMap=!!er&&!!mapr&&Math.abs(er.top-mapr.bottom)<3;const panelInside=!!panel&&panel.parentElement===territory;const cardInside=!!card&&card.parentElement===entity;const csT=territory&&w.getComputedStyle(territory),csE=entity&&w.getComputedStyle(entity);const floating=!!csT&&!!csE&&csT.boxShadow!=='none'&&csE.boxShadow!=='none'&&csT.backgroundImage!=='none'&&csE.backgroundImage!=='none';const nationalStartup=w.__AGWORLD_TERRITORY_STARTUP__==='NATIONAL'||w.__AGWORLD_TERRITORY_STARTUP__==='NATIONAL_THEN_TERRITORY';const entityVisible=!!card&&w.getComputedStyle(card).display!=='none';const state=(leftOrder&&topOrder&&bottomAligned&&territoryUnderLeft&&entityUnderMap&&panelInside&&cardInside&&floating&&nationalStartup)?'pass':'warn';return {name:'FINAL SCREEN LAYOUT & COMMAND PANELS',state,items:[['Sidebar → Missions contiguous',leftOrder],['Missions → Map contiguous',topOrder],['Territory/entity top aligned',bottomAligned],['Territory directly below left stage',territoryUnderLeft],['Entity directly below map',entityUnderMap],['Territory panel contained',panelInside],['Entity card contained',cardInside],['Floating 3D territory panel',floating],['National startup baseline',nationalStartup],['Current territory scope',w.__AGWORLD_TERRITORY_SCOPE__||'INITIALISING'],['Entity card visible',entityVisible],['Shell geometry',shell?Math.round(shell.getBoundingClientRect().width)+' × '+Math.round(shell.getBoundingClientRect().height):'Unavailable']]}})()];return {w,counts,rels,events,checks}}
function fleetApi(w){return w.AGWorldFleetUI||null}
function selectedFleetEntity(w){return fleetApi(w)?.selected?.()||null}
function setFleetStatus(message,state=''){const el=$('fleetDevStatus');if(!el)return;el.textContent=message;el.className='population-status '+state}
function syncFleetControls(){const w=root(),api=fleetApi(w),selectedEntity=selectedFleetEntity(w);const ids=['fleetReassert','fleetOpenSell','fleetOpenHistory'];ids.forEach(id=>{const b=$(id);if(b)b.disabled=!(api&&selectedEntity)});if(!api){setFleetStatus(opener()?'WAITING · Fleet public bridge is not ready yet.':'OPEN THIS PAGE FROM AG WORLD to access the live Fleet system.','warn');return}if(!selectedEntity){setFleetStatus('READY · Fleet system is available. Select a Farm or Contractor in the AG World tab, then return here.','warn');$('fleetDevNote').textContent='No eligible Farm or Contractor is currently selected.';return}setFleetStatus('SELECTED · '+selectedEntity.type.toUpperCase()+' · '+(selectedEntity.name||selectedEntity.id)+' · Fleet controls can now be tested.','ready');$('fleetDevNote').textContent='Selected entity ID: '+selectedEntity.id}
function fleetOverlayReady(w,el){
  if(!el)return false;
  const cs=w.getComputedStyle?.(el);
  return !!cs && cs.position==='fixed' && Number(cs.zIndex||0)>=1000;
}
function fleetModalState(w,el){
  if(!el)return 'MISSING';
  return el.hidden?'CLOSED':'OPEN';
}
function checkFleetSystem(){
  const w=root(),api=fleetApi(w),sell=!!w.openFleetTransaction,history=!!w.openFleetManagement,
    tx=w.document?.getElementById('fleetTransactionModal'),mg=w.document?.getElementById('fleetManagementModal');
  let health=null;
  try{health=api?.health?.({repair:true})||null}catch(e){capture('FLEET HEALTH',e?.message||e)}
  const ui=health?.healthy===true;
  const txOverlay=fleetOverlayReady(w,tx),mgOverlay=fleetOverlayReady(w,mg);
  const pass=!!(api&&sell&&history&&tx&&mg&&ui&&txOverlay&&mgOverlay);
  setFleetStatus((pass?'PASS · ':'WARN · ')+'API: '+(sell?'SELL OK':'SELL MISSING')+' · '+(history?'HISTORY OK':'HISTORY MISSING')+' · Transaction: '+(txOverlay?'OVERLAY READY':'OVERLAY STYLE FAILED')+' ('+fleetModalState(w,tx)+') · History: '+(mgOverlay?'OVERLAY READY':'OVERLAY STYLE FAILED')+' ('+fleetModalState(w,mg)+') · Visible Fleet UI: '+(ui?'READY':'NOT READY'),pass?'ready':'warn');
  syncFleetControls();
  return {...(health||{}),transactionOverlayReady:txOverlay,historyOverlayReady:mgOverlay,transactionModalState:fleetModalState(w,tx),historyModalState:fleetModalState(w,mg)};
}
function fleetSelectedOrWarn(){const w=root(),s=selectedFleetEntity(w);if(!s)throw new Error('Select a Farm or Contractor in AG World first.');return {w,s}}
function reassertFleet(){try{const {w,s}=fleetSelectedOrWarn();const r=fleetApi(w).ensureQuickActions(s.type,s.id);setFleetStatus('BUTTONS REASSERTED · '+s.name+' now has the dedicated Fleet quick-action host.','ready');checkFleetSystem();return r}catch(e){setFleetStatus('REASSERT FAILED · '+(e?.message||e),'error');capture('FLEET UI',e?.message||e)}}
function openFleetSellFromDev(){
  try{
    const {w,s}=fleetSelectedOrWarn(); w.openFleetTransaction(s.type,s.id);
    const modal=w.document?.getElementById('fleetTransactionModal');
    if(!modal||modal.hidden)throw new Error('Transaction action ran but the modal did not enter OPEN state.');
    setFleetStatus('PASS · TRANSACTION MODAL OPEN and visible overlay style verified.','ready');
  }catch(e){setFleetStatus('SELL TEST FAILED · '+(e?.message||e),'error');capture('FLEET SELL',e?.message||e)}
}
async function openFleetHistoryFromDev(){
  try{
    const {w,s}=fleetSelectedOrWarn(); await w.openFleetManagement(s.type,s.id);
    const modal=w.document?.getElementById('fleetManagementModal');
    if(!modal||modal.hidden)throw new Error('History action ran but the modal did not enter OPEN state.');
    setFleetStatus('PASS · FLEET HISTORY MODAL OPEN and visible overlay style verified.','ready');
  }catch(e){setFleetStatus('HISTORY TEST FAILED · '+(e?.message||e),'error');capture('FLEET HISTORY',e?.message||e)}
}

function populationReady(w){return !!(w.AGWorldDemoWorldSeed?.run && w.AGWorldDynamicEntityAPI?.create && w.AGWorldDynamicEntityAPI?.createRelationship && w.AGWorldDynamicEntityAPI?.repairUniqueContractorFarmAssignments && w.AGWorldDynamicEntityAPI?.snapshotExistingAsDemo)}
function setPopulationStatus(message,state=''){const el=$('populationStatus');if(!el)return;el.textContent=message;el.className='population-status '+state}
function syncPopulationControls(){const w=root(),ready=populationReady(w),connected=!!opener();const run=$('populationRun'),repair=$('populationRepair'),demo=$('populationDemo');if(!run)return;if(ready){setPopulationStatus('SYSTEM STABLE · Creation services ready. The live map remains idle until you explicitly start a process.','ready')}else if(connected){setPopulationStatus('WAITING · AG World is still initialising its creation services.','warn')}else{setPopulationStatus('OPEN THIS PAGE FROM THE AG WORLD DEVELOPER MODE MENU to access live population controls.','warn')}[run,repair,demo].forEach(b=>b.disabled=!ready)}
async function runPopulation(){const w=root();if(!populationReady(w))return;if(!confirm('Create the 5 Company Facilities and 50 Contractors now? This is a controlled, one-time demo population process.'))return;const b=$('populationRun');b.disabled=true;b.textContent='POPULATING WORLD…';setPopulationStatus('POPULATION STARTED · The map remains interactive while entities and relationships are created.');try{const r=await w.AGWorldDemoWorldSeed.run();setPopulationStatus('COMPLETE · '+r.facilities+' facilities and '+r.contractors+' contractors processed.','ready');b.textContent='WORLD POPULATED'}catch(e){setPopulationStatus('FAILED · '+(e?.message||'Unknown error'),'error');b.disabled=false;b.textContent='RETRY CONTROLLED POPULATION';capture('POPULATION',e?.message||e)}}
async function repairPopulation(){const w=root();if(!populationReady(w))return;const b=$('populationRepair');b.disabled=true;b.textContent='CHECKING ASSIGNMENTS…';try{const p=await w.AGWorldDynamicEntityAPI.repairUniqueContractorFarmAssignments({preview:true});if(!p.conflictingFarms){setPopulationStatus('CHECK COMPLETE · '+p.farmsChecked+' Farm assignments checked. No duplicate active Contractor assignments were found.','ready');b.textContent='ASSIGNMENTS ALREADY VALID';return}if(!confirm(p.conflictingFarms+' Farms have duplicate active Contractor assignments. '+p.duplicateRelationships+' duplicate relationships will be made inactive, keeping one active Contractor per Farm. Continue?')){setPopulationStatus('REPAIR CANCELLED · No relationships were changed.','warn');b.disabled=false;b.textContent='CHECK & REPAIR FARM ASSIGNMENTS';return}b.textContent='REPAIRING…';const r=await w.AGWorldDynamicEntityAPI.repairUniqueContractorFarmAssignments();setPopulationStatus('REPAIR COMPLETE · '+r.conflictingFarms+' Farms reconciled · '+r.deactivated.length+' duplicate assignments made inactive.','ready');b.textContent='ASSIGNMENTS REPAIRED'}catch(e){setPopulationStatus('REPAIR FAILED · '+(e?.message||'Unknown error'),'error');b.disabled=false;b.textContent='RETRY ASSIGNMENT REPAIR';capture('REPAIR',e?.message||e)}}
async function snapshotCompetitors(){const w=root();if(!populationReady(w))return;if(!confirm('Mark all currently existing Competitor records as DEMO data? Future user-created entities will remain live.'))return;const b=$('populationDemo');b.disabled=true;b.textContent='MARKING DEMO BASELINE…';try{const r=await w.AGWorldDynamicEntityAPI.snapshotExistingAsDemo('competitor');setPopulationStatus('DEMO BASELINE CAPTURED · '+r.marked+' existing Competitor records marked as demo data.','ready');b.textContent='COMPETITOR DEMO BASELINE SAVED';$('populationNote').textContent='Current Farms and seeded Contractors are already demo records. Current Competitors are now explicitly classified as demo. Future user-created entities are saved as live.'}catch(e){setPopulationStatus('DEMO BASELINE FAILED · '+(e?.message||'Unknown error'),'error');b.disabled=false;b.textContent='RETRY DEMO BASELINE';capture('DEMO BASELINE',e?.message||e)}}
function render(){const d=diag();$('connectionState').textContent=opener()?'CONNECTED TO AG WORLD TAB':'STANDALONE MODE';$('connectionState').style.color=opener()?'var(--green)':'var(--amber)';$('appStatus').textContent=d.w.AG_WORLD_WORLD?'LIVE':'LIMITED';$('mapStatus').textContent=d.checks[1].items[0][1]?'READY':'MISSING';$('entityTotal').textContent=d.counts.total;$('relationshipTotal').textContent=d.rels.length;$('eventTotal').textContent=d.events.length;$('errorTotal').textContent=errors.length;
$('diagnosticPanels').innerHTML=d.checks.map((p,i)=>'<article class="panel" data-state="'+p.state+'" data-filter="'+p.state+'"><div class="panel-head" data-toggle="'+i+'"><div><span class="eyebrow">DIAGNOSTIC '+String(i+1).padStart(2,'0')+'</span><h2>'+p.name+'</h2></div><span class="badge '+p.state+'">'+p.state.toUpperCase()+'</span></div><div class="panel-body"><div class="checks">'+p.items.map(([k,v])=>'<div class="check"><span>'+k+'</span><b class="'+(v===false||v==='No map'||v==='Unavailable'?'bad':v==='Check manually'||v==='Not exposed'?'warning':'ok')+'">'+String(v)+'</b></div>').join('')+'</div></div></article>').join('');
document.querySelectorAll('[data-toggle]').forEach(el=>el.onclick=()=>el.closest('.panel').classList.toggle('collapsed'));renderErrors();renderStorage();syncPopulationControls();syncFleetControls()}
function renderErrors(){$('errorLog').textContent=errors.length?errors.map(e=>'['+e.time+'] '+e.type+'\n'+e.message).join('\n\n'):'No errors captured.'}
function renderStorage(){const w=root();const out=[];try{for(let i=0;i<w.localStorage.length;i++){const k=w.localStorage.key(i);let v=w.localStorage.getItem(k)||'';out.push('<div><small>'+esc(k)+'</small><code>'+esc(v.slice(0,500))+(v.length>500?'…':'')+'</code></div>')}}catch(e){out.push('<div>Storage unavailable</div>')}$('storageState').innerHTML=out.length?out.join(''):'No local application state found.'}
function esc(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function capture(type,message){errors.unshift({time:new Date().toLocaleTimeString(),type,message:String(message)});if(errors.length>100)errors.pop();renderErrors();$('errorTotal').textContent=errors.length}
window.addEventListener('error',e=>capture('ERROR',e.message));window.addEventListener('unhandledrejection',e=>capture('PROMISE',e.reason?.message||e.reason));
$('fleetCheck').onclick=checkFleetSystem;$('fleetReassert').onclick=reassertFleet;$('fleetOpenSell').onclick=openFleetSellFromDev;$('fleetOpenHistory').onclick=openFleetHistoryFromDev;$('populationRun').onclick=runPopulation;$('populationRepair').onclick=repairPopulation;$('populationDemo').onclick=snapshotCompetitors;$('refreshDiagnostics').onclick=render;$('refreshStorage').onclick=renderStorage;$('clearErrors').onclick=()=>{errors=[];renderErrors();$('errorTotal').textContent='0'};$('toggleAuto').onclick=e=>{auto=!auto;e.currentTarget.textContent='AUTO REFRESH: '+(auto?'ON':'OFF')};$('expandAll').onclick=()=>document.querySelectorAll('.panel').forEach(x=>x.classList.remove('collapsed'));$('collapseAll').onclick=()=>document.querySelectorAll('.panel').forEach(x=>x.classList.add('collapsed'));document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const f=b.dataset.filter;document.querySelectorAll('.panel[data-filter]').forEach(p=>p.style.display=f==='all'||p.dataset.filter===f?'block':'none')});setInterval(()=>{if(auto)render();else {syncPopulationControls();syncFleetControls()}},2500);render()})();