/* AG WORLD — strategy-game HUD. Inspired by the information hierarchy of 4X strategy games such as Civilization VI, but designed as an original AG WORLD interface and vocabulary. */
(() => {
const css=`
/* Hard reset of the retired HUD. Only the .ag-hud interface may remain visible. */
.game-hud,.game-brand,.player-hud,.mission-hud,.world-control{display:none!important}
body{display:block!important;background:#000!important}.app-shell{position:fixed!important;inset:0!important;width:100vw!important;height:100vh!important;max-width:none!important;max-height:none!important;margin:0!important;border-radius:0!important;background:#000!important;box-shadow:none!important}.sidebar,.missions,.bottom,.map-header,.map-status,.farm-card{display:none!important}.map-area{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;background:#000!important}.map{position:absolute!important;inset:0!important;width:100%!important;height:100%!important}
.ag-hud{position:fixed;inset:0;z-index:30;pointer-events:none;color:#f2f1e9;font-family:Georgia,'Times New Roman',serif;text-shadow:0 1px 2px #000}.ag-hud button{font:inherit;color:inherit}
.ag-topbar{position:absolute;top:0;left:0;right:0;height:58px;background:linear-gradient(180deg,rgba(8,12,13,.94),rgba(8,12,13,.68),transparent);display:flex;align-items:flex-start;padding:0 18px;gap:12px;pointer-events:auto}.ag-emblem{height:42px;min-width:132px;margin-top:7px;padding:0 15px;border-right:1px solid rgba(210,211,187,.25);display:flex;align-items:center;gap:9px}.ag-emblem-mark{width:29px;height:29px;border:2px solid #c6d64b;border-radius:50%;display:grid;place-items:center;color:#c6d64b;font-weight:900;font-size:12px}.ag-emblem-title{font-size:17px;font-weight:900;letter-spacing:2px}.ag-emblem-title b{color:#c6d64b}.ag-resource{height:42px;margin-top:7px;padding:0 16px;border-right:1px solid rgba(210,211,187,.18);min-width:105px;display:flex;flex-direction:column;justify-content:center}.ag-resource span{font:700 8px Arial,sans-serif;letter-spacing:1.4px;color:#aeb5aa}.ag-resource strong{font-size:16px;line-height:17px;color:#f2f1e9}.ag-resource strong em{font-style:normal;color:#c6d64b;font-size:10px;margin-left:3px}.ag-top-spacer{flex:1}.ag-turn{margin-top:8px;text-align:right;min-width:120px}.ag-turn small{display:block;font:700 8px Arial,sans-serif;letter-spacing:1.5px;color:#aeb5aa}.ag-turn strong{font-size:14px;color:#d7d8c8}.ag-menu-button{margin-top:8px;width:42px;height:42px;border:1px solid rgba(214,213,188,.35);background:rgba(8,12,13,.7);cursor:pointer;font:700 16px Arial,sans-serif}
.ag-leader{position:absolute;left:18px;top:76px;width:285px;min-height:82px;background:linear-gradient(110deg,rgba(12,17,18,.94),rgba(17,21,19,.72));border:1px solid rgba(206,207,181,.4);box-shadow:0 8px 24px rgba(0,0,0,.48);pointer-events:auto;display:flex;padding:9px;box-sizing:border-box}.ag-portrait{width:62px;height:62px;border-radius:50%;flex:none;border:2px solid #c6d64b;background:radial-gradient(circle at 50% 34%,#b98e6b 0 17%,transparent 17.5%),radial-gradient(ellipse at 50% 75%,#3f4d4d 0 38%,transparent 38.5%),linear-gradient(145deg,#79867f,#172326);position:relative;overflow:hidden}.ag-portrait:before{content:'';position:absolute;width:42px;height:24px;left:8px;top:16px;border-radius:50%;background:#292623}.ag-portrait:after{content:'';position:absolute;width:51px;height:20px;left:3px;top:7px;border:4px solid #c7b69b;border-bottom:0;border-radius:50%;opacity:.9}.ag-leader-info{padding:2px 0 0 11px;flex:1}.ag-leader-name{font-size:18px;font-weight:900;letter-spacing:1px}.ag-leader-role{font:700 8px Arial,sans-serif;letter-spacing:1px;color:#b4bbb3;margin-top:2px}.ag-level{font:700 9px Arial,sans-serif;letter-spacing:1px;color:#c6d64b;margin-top:9px}.ag-xp{height:5px;background:#27302b;margin-top:4px}.ag-xp i{display:block;height:100%;width:84.2%;background:#c6d64b}.ag-xptext{font:700 7px Arial,sans-serif;color:#c9cec7;margin-top:3px}
.ag-objective{position:absolute;right:18px;top:76px;width:300px;pointer-events:auto}.ag-objective-main{width:100%;min-height:82px;box-sizing:border-box;background:linear-gradient(110deg,rgba(12,17,18,.95),rgba(17,21,19,.72));border:1px solid rgba(206,207,181,.42);padding:11px 38px 10px 47px;text-align:left;position:relative;cursor:pointer;box-shadow:0 8px 24px rgba(0,0,0,.48)}.ag-objective-icon{position:absolute;left:13px;top:15px;width:23px;height:23px;border:2px solid #c6d64b;border-radius:50%}.ag-objective-icon:before{content:'';position:absolute;inset:6px;border:1px solid #c6d64b;border-radius:50%}.ag-objective-label{display:block;font:900 8px Arial,sans-serif;letter-spacing:1.6px;color:#c6d64b}.ag-objective-title{display:block;margin-top:7px;font-size:15px;font-weight:900}.ag-objective-sub{display:block;margin-top:4px;font:700 8px Arial,sans-serif;color:#b9c0b8}.ag-objective-arrow{position:absolute;right:13px;top:30px;color:#c6d64b;font:700 16px Arial,sans-serif}.ag-objective-panel{display:none;background:rgba(9,13,14,.97);border:1px solid rgba(206,207,181,.35);border-top:0;padding:13px}.ag-objective.open .ag-objective-panel{display:block}.ag-objective-panel h4{margin:0;color:#c6d64b;font:900 8px Arial,sans-serif;letter-spacing:1.5px}.ag-objective-panel p{font-size:11px;line-height:1.4;margin:7px 0;color:#d4d7cf}.ag-objective-panel div{font:700 8px Arial,sans-serif;color:#b5bcb5;padding:5px 0;border-top:1px solid rgba(255,255,255,.09)}
.ag-world{position:absolute;left:20px;bottom:19px;width:275px;height:118px;pointer-events:auto}.ag-minimap{position:absolute;left:0;bottom:0;width:104px;height:104px;border-radius:50%;border:2px solid #c6d64b;background:radial-gradient(circle at 35% 28%,#5c7373,#203e43 37%,#0b2027 72%,#03090c);box-shadow:0 8px 28px rgba(0,0,0,.68),inset -15px -15px 24px rgba(0,0,0,.5);cursor:pointer;overflow:hidden}.ag-minimap:before{content:'';position:absolute;inset:12px;border-radius:50%;background:linear-gradient(160deg,#365a62,#102d35 60%,#07161d);box-shadow:inset 10px 8px 15px rgba(255,255,255,.1),inset -12px -15px 18px rgba(0,0,0,.55)}.ag-minimap:after{content:'SA';position:absolute;left:37px;top:41px;color:rgba(207,218,132,.65);font:900 15px Arial,sans-serif;letter-spacing:2px}.ag-world-label{position:absolute;left:76px;bottom:14px;width:178px;height:48px;background:rgba(8,12,13,.88);border:1px solid rgba(206,207,181,.38);border-left:0;padding:9px 17px;box-sizing:border-box}.ag-world-label strong{display:block;font:900 10px Arial,sans-serif;letter-spacing:1.5px;color:#c6d64b}.ag-world-label span{display:block;font:700 8px Arial,sans-serif;color:#b8beb7;margin-top:3px}.ag-world-menu{display:none;position:absolute;left:75px;bottom:64px;width:200px;background:rgba(8,12,13,.97);border:1px solid rgba(206,207,181,.4);padding:7px;box-shadow:0 12px 35px #000}.ag-world.open .ag-world-menu{display:grid;gap:4px}.ag-world-menu button{background:rgba(255,255,255,.035);border:1px solid rgba(255,255,255,.08);padding:8px;text-align:left;font:700 8px Arial,sans-serif;cursor:pointer}.ag-world-menu button:hover{border-color:#c6d64b;color:#c6d64b}
.ag-actions{position:absolute;right:18px;bottom:19px;width:315px;pointer-events:auto}.ag-selected{background:linear-gradient(110deg,rgba(10,15,16,.96),rgba(18,22,20,.82));border:1px solid rgba(206,207,181,.38);padding:9px 12px;margin-bottom:7px;min-height:45px;box-sizing:border-box}.ag-selected small{display:block;font:700 7px Arial,sans-serif;letter-spacing:1.5px;color:#aeb5ad}.ag-selected strong{font-size:15px}.ag-selected em{float:right;color:#c6d64b;font:900 10px Arial,sans-serif;margin-top:4px;font-style:normal}.ag-action-row{display:flex;justify-content:flex-end;gap:5px}.ag-action{width:47px;height:47px;background:rgba(8,12,13,.91);border:1px solid rgba(206,207,181,.38);cursor:pointer;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px}.ag-action .ico{font:900 17px Arial,sans-serif;color:#c6d64b}.ag-action span{font:900 6px Arial,sans-serif;letter-spacing:.8px;color:#d0d3ca}.ag-action:hover{border-color:#c6d64b;background:rgba(32,40,32,.94)}
.ag-filter{position:absolute;right:18px;bottom:78px;width:270px;background:rgba(7,11,12,.98);border:1px solid rgba(198,214,75,.6);box-shadow:0 14px 40px rgba(0,0,0,.72);padding:14px;box-sizing:border-box;display:none;pointer-events:auto}.ag-filter.open{display:block}.ag-filter-head{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid rgba(255,255,255,.1);padding-bottom:9px}.ag-filter-head strong{font:900 10px Arial,sans-serif;letter-spacing:1.6px;color:#c6d64b}.ag-filter-head button{border:0;background:none;color:#aeb5ad;cursor:pointer;font:700 16px Arial}.ag-filter-note{font:700 8px Arial,sans-serif;color:#929b94;line-height:1.4;margin:9px 0}.ag-filter-grid{display:grid;gap:6px}.ag-filter-item{display:flex;align-items:center;gap:9px;padding:6px 4px;font:700 9px Arial,sans-serif;color:#d8dbd4;cursor:pointer}.ag-filter-item input{appearance:none;width:15px;height:15px;border:1px solid #778078;background:#111718;position:relative}.ag-filter-item input:checked{border-color:#c6d64b;background:#38401d}.ag-filter-item input:checked:after{content:'✓';position:absolute;left:2px;top:-1px;color:#c6d64b;font-weight:900}.ag-filter-item.territory{border-bottom:1px solid rgba(255,255,255,.1);padding-bottom:9px;margin-bottom:2px}.ag-filter-legend{display:flex;gap:15px;margin-top:10px;padding-top:9px;border-top:1px solid rgba(255,255,255,.1);font:700 7px Arial,sans-serif;color:#b5bbb4}.ag-dot{width:8px;height:8px;border-radius:50%;display:inline-block;margin-right:4px}.ag-green{background:#58c765}.ag-red{background:#e24b4b}
.ag-notices{position:absolute;right:18px;top:170px;width:210px;display:grid;gap:5px;pointer-events:none}.ag-notice{background:rgba(8,12,13,.78);border-left:2px solid rgba(198,214,75,.7);padding:7px 9px}.ag-notice small{font:900 6px Arial,sans-serif;letter-spacing:1.2px;color:#c6d64b}.ag-notice span{display:block;font:700 8px Arial,sans-serif;color:#d3d7d0;margin-top:2px}
@media(max-width:900px){.ag-topbar{transform:scale(.82);transform-origin:top left;width:122%}.ag-leader{top:62px;left:10px;transform:scale(.82);transform-origin:top left}.ag-objective{top:62px;right:10px;transform:scale(.82);transform-origin:top right}.ag-actions{right:10px;bottom:10px;transform:scale(.82);transform-origin:bottom right}.ag-world{left:10px;bottom:10px;transform:scale(.82);transform-origin:bottom left}.ag-notices{right:10px;top:145px;transform:scale(.78);transform-origin:top right}}
`;
function install(){
if(document.querySelector('.ag-hud'))return;const style=document.createElement('style');style.id='ag-world-game-hud-style';style.textContent=css;document.head.appendChild(style);
const hud=document.createElement('div');hud.className='ag-hud';hud.innerHTML=`
<header class="ag-topbar"><div class="ag-emblem"><div class="ag-emblem-mark">AG</div><div class="ag-emblem-title"><b>AG</b> WORLD</div></div><div class="ag-resource"><span>TERRITORY</span><strong>03 <em>74%</em></strong></div><div class="ag-resource"><span>CONTROLLED FARMS</span><strong>18 <em>+2</em></strong></div><div class="ag-resource"><span>DRONE FLEET</span><strong>27 <em>ACTIVE</em></strong></div><div class="ag-resource"><span>OPPORTUNITIES</span><strong>14 <em>HIGH</em></strong></div><div class="ag-top-spacer"></div><div class="ag-turn"><small>OPERATIONS DAY</small><strong>DAY 12 · 08:42</strong></div><button class="ag-menu-button" aria-label="Game menu">☰</button></header>
<section class="ag-leader"><div class="ag-portrait"></div><div class="ag-leader-info"><div class="ag-leader-name">NICO</div><div class="ag-leader-role">SALES REPRESENTATIVE · TERRITORY 03</div><div class="ag-level">LEVEL 12</div><div class="ag-xp"><i></i></div><div class="ag-xptext">8,420 / 10,000 XP</div></div></section>
<section class="ag-objective"><button class="ag-objective-main"><i class="ag-objective-icon"></i><span class="ag-objective-label">ACTIVE OBJECTIVE</span><span class="ag-objective-title">MEET YOUR TERRITORY</span><span class="ag-objective-sub">2 objectives remaining</span><b class="ag-objective-arrow">⌄</b></button><div class="ag-objective-panel"><h4>STRATEGIC OBJECTIVE</h4><p>Understand the territory, identify the highest-value uncovered farm and establish the next commercial relationship.</p><div>○ Identify assigned territory</div><div>○ Visit first target farm</div><div>○ Record the opportunity</div></div></section>
<section class="ag-notices"><div class="ag-notice"><small>AI INTELLIGENCE</small><span>1 high-value farm is uncovered nearby.</span></div><div class="ag-notice"><small>TERRITORY</small><span>New drone coverage recorded.</span></div></section>
<section class="ag-world"><button class="ag-minimap" aria-label="Open world map"></button><div class="ag-world-label"><strong>WORLD MAP</strong><span>South Africa · Territory view</span></div><nav class="ag-world-menu"><button data-game-view="territory">◎ TERRITORY MAP</button><button data-game-view="farms">◇ MY FARMS</button><button data-game-view="opportunities">◆ OPPORTUNITIES</button><button data-game-view="customers">● CUSTOMERS</button><button data-game-view="missions">★ MISSIONS</button><button data-game-view="training">△ TRAINING</button></nav></section>
<section class="ag-actions"><div class="ag-selected"><small>SELECTED TERRITORY</small><strong id="ag-selected-name">SOUTH AFRICA</strong><em id="ag-selected-state">NATIONAL VIEW</em></div><div class="ag-action-row"><button class="ag-action" data-action="territory"><i class="ico">◈</i><span>TERRITORY</span></button><button class="ag-action" data-action="farms"><i class="ico">⌂</i><span>FARMS</span></button><button class="ag-action" data-action="missions"><i class="ico">◆</i><span>MISSIONS</span></button><button class="ag-action" data-action="ai"><i class="ico">✦</i><span>AI MOVE</span></button><button class="ag-action" id="agFilterButton" aria-label="Map data filters"><i class="ico">⌕</i><span>DATA LENS</span></button></div></section>
<aside class="ag-filter" id="agFilterPanel"><div class="ag-filter-head"><strong>MAP DATA LAYERS</strong><button id="agFilterClose">×</button></div><div class="ag-filter-note">Select the intelligence layers you want visible on the strategic map. Layers use the live AG WORLD farm records.</div><div class="ag-filter-grid"><label class="ag-filter-item territory"><input type="checkbox" data-layer="territory" checked><span>TERRITORY CONTROL</span></label><label class="ag-filter-item"><input type="checkbox" data-layer="farms" checked><span>FARMS</span></label><label class="ag-filter-item"><input type="checkbox" data-layer="opportunities" checked><span>SALES OPPORTUNITIES</span></label><label class="ag-filter-item"><input type="checkbox" data-layer="company-drones" checked><span>COMPANY DRONES</span></label><label class="ag-filter-item"><input type="checkbox" data-layer="competitor-drones"><span>COMPETITOR DRONES</span></label><label class="ag-filter-item"><input type="checkbox" data-layer="crops"><span>CROPS / FIELDS</span></label><label class="ag-filter-item"><input type="checkbox" data-layer="livestock"><span>LIVESTOCK</span></label><label class="ag-filter-item"><input type="checkbox" data-layer="machinery"><span>MACHINERY</span></label><label class="ag-filter-item"><input type="checkbox" data-layer="water"><span>WATER / IRRIGATION</span></label><label class="ag-filter-item"><input type="checkbox" data-layer="infrastructure"><span>BUILDINGS / INFRASTRUCTURE</span></label><label class="ag-filter-item"><input type="checkbox" data-layer="provinces" checked><span>PROVINCIAL BOUNDARIES</span></label></div><div class="ag-filter-legend"><span><i class="ag-dot ag-green"></i>DRONE PENETRATED</span><span><i class="ag-dot ag-red"></i>UNCOVERED</span></div></aside>`;
document.body.appendChild(hud);
const objective=hud.querySelector('.ag-objective');hud.querySelector('.ag-objective-main').addEventListener('click',()=>objective.classList.toggle('open'));const world=hud.querySelector('.ag-world');hud.querySelector('.ag-minimap').addEventListener('click',()=>world.classList.toggle('open'));const filter=hud.querySelector('#agFilterPanel');hud.querySelector('#agFilterButton').addEventListener('click',()=>filter.classList.toggle('open'));hud.querySelector('#agFilterClose').addEventListener('click',()=>filter.classList.remove('open'));
hud.querySelectorAll('[data-game-view]').forEach(btn=>btn.addEventListener('click',()=>{world.classList.remove('open');const id=btn.dataset.gameView;if(id==='territory')document.getElementById('nationalBtn')?.click();else if(id==='missions')objective.classList.add('open');else if(window.showToast)window.showToast(btn.textContent.trim()+' opened')}));
hud.querySelectorAll('[data-action]').forEach(btn=>btn.addEventListener('click',()=>{const action=btn.dataset.action;if(action==='territory')document.getElementById('nationalBtn')?.click();else if(action==='ai')document.getElementById('aiAction')?.click();else if(window.showToast)window.showToast(btn.querySelector('span').textContent+' selected')}));
hud.querySelectorAll('[data-layer]').forEach(input=>input.addEventListener('change',()=>window.agWorldSetLayerVisibility?.(input.dataset.layer,input.checked)));
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
