/* AG World game HUD — master in-game HUD based on the supplied reference images. */
(() => {
  const css = `
  body{display:block!important;background:#000!important}.app-shell{position:fixed!important;inset:0!important;width:100vw!important;height:100vh!important;max-width:none!important;max-height:none!important;margin:0!important;box-shadow:none!important;border-radius:0!important;background:#000!important}.sidebar,.missions,.bottom{display:none!important}.map-area{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;background:#000!important}.map-header,.map-status,.farm-card{display:none!important}.map{position:absolute!important;inset:0!important;width:100%!important;height:100%!important}
  .game-hud{position:fixed;inset:0;z-index:20;pointer-events:none;font-family:Arial,Helvetica,sans-serif;color:#fff}.game-brand{position:absolute;left:50%;top:9.2%;transform:translateX(-50%);font-size:clamp(40px,5.2vw,86px);font-weight:900;letter-spacing:6px;color:rgba(244,244,235,.84);text-shadow:0 4px 15px rgba(0,0,0,.9),0 0 2px #000;white-space:nowrap}
  .player-hud{position:absolute;top:24px;left:24px;width:350px;height:106px;box-sizing:border-box;padding:15px 52px 12px 108px;background:linear-gradient(105deg,rgba(7,12,15,.96),rgba(8,14,17,.76));border:1px solid rgba(196,216,76,.68);border-radius:8px;box-shadow:0 10px 32px rgba(0,0,0,.52);pointer-events:auto;backdrop-filter:blur(8px)}.player-avatar{position:absolute;left:10px;top:10px;width:84px;height:84px;border-radius:50%;overflow:hidden;border:2px solid #c5d94c;background:radial-gradient(circle at 50% 37%,#b78d6c 0 16%,transparent 16.5%),radial-gradient(ellipse at 50% 75%,#39484c 0 38%,transparent 38.5%),linear-gradient(145deg,#7d8a85,#1c282c);box-shadow:0 0 0 3px rgba(197,217,76,.12),inset -9px -12px 16px rgba(0,0,0,.32)}.player-avatar:before{content:'';position:absolute;width:46px;height:26px;left:19px;top:19px;border-radius:50% 50% 38% 38%;background:#292522;transform:rotate(-3deg)}.player-avatar:after{content:'';position:absolute;width:55px;height:22px;left:14px;top:9px;border-radius:50%;border:5px solid #c9b99f;border-bottom:0;opacity:.92}.player-name{font-size:18px;font-weight:900;letter-spacing:1.7px}.player-role{font-size:8px;color:#aab6b5;letter-spacing:1.35px;text-transform:uppercase;margin-top:4px}.player-level{margin-top:8px;font-size:11px;color:#c8db4d;font-weight:900;letter-spacing:1.1px}.player-xp{height:6px;background:#26322c;border-radius:99px;overflow:hidden;margin-top:4px}.player-xp span{display:block;width:84.2%;height:100%;background:#c5d94c}.player-xp-text{font-size:9px;color:#dce1dd;margin-top:4px}.player-badge{position:absolute;right:14px;bottom:13px;width:28px;height:32px;border:2px solid #c5d94c;clip-path:polygon(50% 0,100% 15%,91% 78%,50% 100%,9% 78%,0 15%);display:grid;place-items:center;color:#c5d94c;font-size:12px;background:rgba(197,217,76,.06)}
  .mission-hud{position:absolute;top:24px;right:24px;width:306px;pointer-events:auto}.mission-tab{width:100%;height:106px;box-sizing:border-box;border:1px solid rgba(196,216,76,.68);background:linear-gradient(105deg,rgba(7,12,15,.96),rgba(8,14,17,.78));color:#fff;border-radius:8px;padding:15px 45px 12px 54px;text-align:left;cursor:pointer;box-shadow:0 10px 32px rgba(0,0,0,.52);backdrop-filter:blur(8px);position:relative}.mission-tab:hover{border-color:#d2e75b}.mission-icon{position:absolute;left:16px;top:18px;width:25px;height:25px;border:2px solid #c5d94c;border-radius:50%;box-sizing:border-box}.mission-icon:before,.mission-icon:after{content:'';position:absolute;left:50%;top:50%;background:#c5d94c;transform:translate(-50%,-50%)}.mission-icon:before{width:31px;height:2px}.mission-icon:after{width:2px;height:31px}.mission-label{color:#c5d94c;font-size:9px;font-weight:900;letter-spacing:1.6px}.mission-title{font-size:15px;font-weight:900;letter-spacing:1px;margin-top:11px}.mission-sub{font-size:10px;color:#c5d94c;margin-top:6px}.mission-chevron{position:absolute;bottom:6px;left:50%;transform:translateX(-50%);color:#c5d94c;font-size:18px;line-height:12px}.mission-hud.open .mission-chevron{transform:translateX(-50%) rotate(180deg)}.mission-panel{display:none;margin-top:7px;padding:15px 17px;background:rgba(7,12,15,.98);border:1px solid rgba(196,216,76,.48);border-radius:8px;box-shadow:0 15px 40px rgba(0,0,0,.6)}.mission-hud.open .mission-panel{display:block}.mission-panel h3{margin:0;color:#c5d94c;font-size:9px;letter-spacing:1.5px}.mission-panel strong{display:block;margin-top:7px;font-size:15px}.mission-panel p{font-size:10px;color:#aeb9b8;line-height:1.45}.mission-objectives{list-style:none;margin:11px 0 0;padding:0}.mission-objectives li{font-size:10px;padding:7px 0;border-top:1px solid rgba(255,255,255,.08)}.mission-reward{margin-top:10px;color:#c5d94c;font-size:9px;font-weight:800}
  .world-control{position:absolute;left:28px;bottom:25px;width:272px;height:116px;pointer-events:auto}.globe-button{position:absolute;left:0;bottom:0;width:106px;height:106px;border-radius:50%;border:1px solid #c5d94c;background:radial-gradient(circle at 32% 23%,rgba(145,170,181,.82),rgba(45,78,85,.78) 28%,rgba(10,28,35,.98) 69%,#02090d 100%);box-shadow:0 0 0 4px rgba(197,217,76,.08),0 12px 34px rgba(0,0,0,.68),inset -17px -15px 26px rgba(0,0,0,.52);cursor:pointer;color:#c5d94c;overflow:hidden}.globe-button:before{content:'';position:absolute;inset:11px;border-radius:50%;background:radial-gradient(ellipse at 24% 39%,rgba(190,204,121,.96) 0 9%,transparent 9.5%),radial-gradient(ellipse at 53% 66%,rgba(77,116,73,.98) 0 13%,transparent 13.5%),radial-gradient(ellipse at 71% 34%,rgba(143,160,88,.92) 0 8%,transparent 8.5%),linear-gradient(155deg,#315a70,#122c39 48%,#06131a);box-shadow:inset 12px 10px 18px rgba(255,255,255,.12),inset -16px -18px 25px rgba(0,0,0,.52)}.globe-button:after{content:'';position:absolute;inset:7px;border-radius:50%;border:1px solid rgba(255,255,255,.2)}.world-label{position:absolute;left:82px;bottom:14px;width:153px;height:51px;box-sizing:border-box;padding:9px 17px;background:rgba(8,13,16,.9);border:1px solid rgba(196,216,76,.65);border-left:0;border-radius:0 27px 27px 0;color:#c5d94c;font-size:11px;font-weight:900;letter-spacing:1.5px;line-height:16px}.world-label:after{content:'⌃';position:absolute;right:40px;bottom:-20px;color:#c5d94c;font-size:21px}.world-menu{display:none;position:absolute;left:84px;bottom:69px;width:210px;padding:9px;background:rgba(7,12,15,.98);border:1px solid rgba(196,216,76,.5);border-radius:9px;box-shadow:0 15px 40px rgba(0,0,0,.65)}.world-control.open .world-menu{display:grid;gap:5px}.world-menu button{border:1px solid rgba(255,255,255,.08);background:rgba(255,255,255,.035);color:#e3e8e4;border-radius:5px;text-align:left;padding:9px 11px;font-size:9px;cursor:pointer}.world-menu button:hover{border-color:#c5d94c;color:#c5d94c}
  @media(max-width:900px){.game-brand{top:12%;font-size:clamp(32px,8vw,58px)}.player-hud{top:12px;left:12px;transform:scale(.8);transform-origin:top left}.mission-hud{top:12px;right:12px;transform:scale(.8);transform-origin:top right}.world-control{left:12px;bottom:12px;transform:scale(.8);transform-origin:bottom left}}
  `;
  const style=document.createElement('style');style.id='ag-world-game-hud-style';style.textContent=css;document.head.appendChild(style);
  function install(){
    if(document.querySelector('.game-hud')) return;
    const hud=document.createElement('div');hud.className='game-hud';hud.innerHTML=`<div class="game-brand"><span>AG</span> WORLD</div><section class="player-hud" aria-label="Player profile"><div class="player-avatar" aria-hidden="true"></div><div class="player-name">NICO</div><div class="player-role">SALES REPRESENTATIVE · TERRITORY 03</div><div class="player-level">LEVEL 12</div><div class="player-xp"><span></span></div><div class="player-xp-text">8,420 / 10,000 XP</div><div class="player-badge">★</div></section><section class="mission-hud" aria-label="Active mission"><button class="mission-tab" type="button"><i class="mission-icon" aria-hidden="true"></i><span class="mission-label">ACTIVE MISSION</span><span class="mission-chevron">⌄</span><div class="mission-title">MEET YOUR TERRITORY</div><div class="mission-sub">2 objectives remaining</div></button><div class="mission-panel"><h3>ACTIVE MISSION</h3><strong>MEET YOUR TERRITORY</strong><p>Your first objective is to understand the territory and identify the highest-value opportunity.</p><ul class="mission-objectives"><li>○ Identify your assigned territory</li><li>○ Visit your first target farm</li><li>○ Record the commercial opportunity</li></ul><div class="mission-reward">REWARD · +850 XP · TERRITORY PROGRESS</div></div></section><section class="world-control" aria-label="World menu"><button class="globe-button" type="button" aria-label="Open world menu"></button><div class="world-label">WORLD<br>MENU</div><nav class="world-menu"><button data-game-view="territory">◎ TERRITORY MAP</button><button data-game-view="farms">◇ MY FARMS</button><button data-game-view="opportunities">◆ OPPORTUNITIES</button><button data-game-view="customers">● CUSTOMERS</button><button data-game-view="missions">★ MISSIONS</button><button data-game-view="training">△ TRAINING</button><button data-game-view="leaderboard">♜ LEADERBOARD</button></nav></section>`;
    document.body.appendChild(hud);
    const mission=hud.querySelector('.mission-hud');hud.querySelector('.mission-tab').addEventListener('click',()=>mission.classList.toggle('open'));
    const world=hud.querySelector('.world-control');hud.querySelector('.globe-button').addEventListener('click',()=>world.classList.toggle('open'));
    hud.querySelectorAll('[data-game-view]').forEach(btn=>btn.addEventListener('click',()=>{world.classList.remove('open');const id=btn.dataset.gameView;if(id==='territory')document.getElementById('nationalBtn')?.click();else if(id==='missions')mission.classList.add('open');else if(window.showToast)window.showToast(btn.textContent.trim()+' opened')}));
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
