/* AG World game HUD — visual reference aligned to the supplied AG WORLD game mockup. */
(() => {
  const css = `
  body{display:block!important;background:#000!important}
  .app-shell{position:fixed!important;inset:0!important;width:100vw!important;height:100vh!important;max-width:none!important;max-height:none!important;margin:0!important;box-shadow:none!important;border-radius:0!important;background:#000!important}
  .sidebar,.missions,.bottom{display:none!important}
  .map-area{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;background:#000!important}
  .map-header,.map-status,.farm-card{display:none!important}
  .map{position:absolute!important;inset:0!important;width:100%!important;height:100%!important}

  .game-hud{position:fixed;inset:0;z-index:20;pointer-events:none;font-family:Arial,Helvetica,sans-serif;color:#fff}
  .game-brand{position:absolute;left:50%;top:8.5%;transform:translateX(-50%);font-size:clamp(42px,5.5vw,92px);font-weight:900;letter-spacing:7px;color:rgba(245,245,235,.82);text-shadow:0 4px 14px rgba(0,0,0,.85),0 0 2px #000;pointer-events:none;white-space:nowrap}.game-brand span{color:#b9ce3e}

  .player-hud{position:absolute;top:22px;left:22px;width:356px;height:108px;box-sizing:border-box;padding:14px 54px 12px 118px;background:linear-gradient(110deg,rgba(9,14,17,.93),rgba(9,14,17,.72));border:1px solid rgba(185,206,62,.58);border-radius:10px;box-shadow:0 10px 32px rgba(0,0,0,.45);pointer-events:auto;backdrop-filter:blur(7px)}
  .player-avatar{position:absolute;left:9px;top:9px;width:90px;height:90px;border-radius:50%;overflow:hidden;border:1px solid #c0d346;box-shadow:0 0 0 3px rgba(185,206,62,.10);background:radial-gradient(circle at 50% 32%,#d6b99c 0 15%,transparent 15.5%),radial-gradient(ellipse at 50% 80%,#4d5960 0 34%,transparent 34.5%),linear-gradient(145deg,#78827b,#1d282c)}
  .player-avatar:before{content:'';position:absolute;width:42px;height:25px;left:24px;top:20px;border-radius:50% 50% 38% 38%;background:#2b2725;transform:rotate(-4deg)}
  .player-avatar:after{content:'';position:absolute;width:54px;height:25px;left:18px;top:11px;border-radius:50%;border:5px solid #d2c6ae;border-bottom:0;transform:rotate(-5deg);opacity:.9}
  .player-name{font-size:19px;font-weight:800;letter-spacing:1.4px}.player-role{font-size:8px;color:#aab5b5;letter-spacing:1.3px;text-transform:uppercase;margin-top:3px}.player-level{margin-top:7px;font-size:12px;color:#c5d94b;font-weight:800;letter-spacing:1px}.player-xp{height:7px;background:#26322c;border-radius:99px;overflow:hidden;margin-top:5px}.player-xp span{display:block;width:84.2%;height:100%;background:linear-gradient(90deg,#8da32d,#c8da4d)}.player-xp-text{font-size:10px;color:#e1e5df;margin-top:4px}.player-badge{position:absolute;right:12px;top:14px;width:27px;height:31px;border:2px solid #c5d94c;clip-path:polygon(50% 0,100% 15%,91% 78%,50% 100%,9% 78%,0 15%);display:grid;place-items:center;color:#c5d94c;font-size:13px;background:rgba(197,217,76,.06)}

  .mission-hud{position:absolute;top:22px;right:22px;width:307px;pointer-events:auto}.mission-tab{width:100%;min-height:108px;box-sizing:border-box;border:1px solid rgba(185,206,62,.55);background:linear-gradient(110deg,rgba(9,14,17,.95),rgba(9,14,17,.78));color:#fff;border-radius:10px;padding:15px 48px 13px 54px;text-align:left;cursor:pointer;box-shadow:0 10px 32px rgba(0,0,0,.45);backdrop-filter:blur(7px);position:relative}.mission-tab:hover{border-color:#c5d94c}.mission-icon{position:absolute;left:15px;top:17px;width:27px;height:27px;border:2px solid #c5d94c;border-radius:50%;box-sizing:border-box}.mission-icon:before,.mission-icon:after{content:'';position:absolute;left:50%;top:50%;background:#c5d94c;transform:translate(-50%,-50%)}.mission-icon:before{width:35px;height:2px}.mission-icon:after{width:2px;height:35px}.mission-label{color:#c5d94c;font-size:10px;font-weight:800;letter-spacing:1.5px;text-transform:uppercase}.mission-title{font-size:16px;font-weight:800;letter-spacing:.9px;margin-top:10px}.mission-sub{font-size:11px;color:#c5d94c;margin-top:6px}.mission-chevron{position:absolute;bottom:7px;left:50%;transform:translateX(-50%);color:#c5d94c;font-size:19px;line-height:12px;transition:transform .2s}.mission-hud.open .mission-chevron{transform:translateX(-50%) rotate(180deg)}
  .mission-panel{display:none;margin-top:7px;padding:16px 18px;background:rgba(9,14,17,.97);border:1px solid rgba(185,206,62,.42);border-radius:10px;box-shadow:0 15px 40px rgba(0,0,0,.55)}.mission-hud.open .mission-panel{display:block}.mission-panel h3{margin:0;color:#c5d94c;font-size:10px;letter-spacing:1.4px}.mission-panel strong{display:block;margin-top:7px;font-size:16px}.mission-panel p{font-size:10px;color:#aeb9b8;line-height:1.45}.mission-objectives{list-style:none;margin:12px 0 0;padding:0}.mission-objectives li{font-size:10px;padding:7px 0;border-top:1px solid rgba(255,255,255,.08)}.mission-reward{margin-top:11px;color:#c5d94c;font-size:10px;font-weight:700}

  .world-control{position:absolute;left:34px;bottom:28px;width:270px;height:120px;pointer-events:auto}.globe-button{position:absolute;left:0;bottom:0;width:116px;height:116px;border-radius:50%;border:1px solid #c5d94c;background:radial-gradient(circle at 34% 25%,rgba(145,170,181,.7),rgba(40,75,82,.75) 28%,rgba(10,28,35,.97) 69%,#02090d 100%);box-shadow:0 0 0 4px rgba(197,217,76,.08),0 12px 34px rgba(0,0,0,.6),inset -17px -15px 26px rgba(0,0,0,.5);cursor:pointer;color:#c5d94c;overflow:hidden}.globe-button:before{content:'';position:absolute;inset:13px;border-radius:50%;background:radial-gradient(ellipse at 25% 40%,rgba(190,204,121,.95) 0 8%,transparent 8.5%),radial-gradient(ellipse at 55% 65%,rgba(77,116,73,.95) 0 11%,transparent 11.5%),radial-gradient(ellipse at 70% 35%,rgba(143,160,88,.9) 0 7%,transparent 7.5%),linear-gradient(155deg,#315a70,#122c39 48%,#06131a);box-shadow:inset 12px 10px 18px rgba(255,255,255,.12),inset -16px -18px 25px rgba(0,0,0,.52)}.globe-button:after{content:'';position:absolute;inset:9px;border-radius:50%;border:1px solid rgba(255,255,255,.18);box-shadow:inset 8px 8px 18px rgba(255,255,255,.08)}
  .world-label{position:absolute;left:91px;bottom:17px;width:144px;height:55px;box-sizing:border-box;padding:10px 18px;background:rgba(9,14,17,.87);border:1px solid rgba(185,206,62,.58);border-left:0;border-radius:0 28px 28px 0;color:#c5d94c;font-size:12px;font-weight:800;letter-spacing:1.4px;line-height:17px;white-space:normal;pointer-events:none}.world-label:after{content:'⌃';position:absolute;right:42px;bottom:-21px;color:#c5d94c;font-size:22px}
  .world-menu{display:none;position:absolute;left:93px;bottom:72px;width:205px;padding:9px;background:rgba(8,13,16,.96);border:1px solid rgba(185,206,62,.48);border-radius:11px;box-shadow:0 15px 40px rgba(0,0,0,.6)}.world-control.open .world-menu{display:grid;gap:5px}.world-menu button{border:1px solid rgba(255,255,255,.08);background:rgba(255,255,255,.035);color:#e3e8e4;border-radius:6px;text-align:left;padding:10px 12px;font-size:10px;cursor:pointer}.world-menu button:hover{border-color:#c5d94c;color:#c5d94c;background:rgba(197,217,76,.06)}

  @media(max-width:900px){.game-brand{top:13%;font-size:clamp(34px,8vw,60px)}.player-hud{top:12px;left:12px;transform:scale(.82);transform-origin:top left}.mission-hud{top:12px;right:12px;transform:scale(.82);transform-origin:top right}.world-control{left:16px;bottom:16px;transform:scale(.82);transform-origin:bottom left}}
  `;
  const style=document.createElement('style'); style.id='ag-world-game-hud-style'; style.textContent=css; document.head.appendChild(style);

  function install(){
    if(document.querySelector('.game-hud')) return;
    const hud=document.createElement('div'); hud.className='game-hud'; hud.innerHTML=`
      <div class="game-brand"><span>AG</span> WORLD</div>
      <section class="player-hud" aria-label="Player profile">
        <div class="player-avatar" aria-hidden="true"></div><div class="player-name">NICO</div><div class="player-role">SALES REPRESENTATIVE · TERRITORY 03</div><div class="player-level">LEVEL 12</div><div class="player-xp"><span></span></div><div class="player-xp-text">8,420 / 10,000 XP</div><div class="player-badge">★</div>
      </section>
      <section class="mission-hud" aria-label="Active mission">
        <button class="mission-tab" type="button"><i class="mission-icon" aria-hidden="true"></i><span class="mission-label">ACTIVE MISSION</span><span class="mission-chevron">⌄</span><div class="mission-title">MEET YOUR TERRITORY</div><div class="mission-sub">2 objectives remaining</div></button>
        <div class="mission-panel"><h3>ACTIVE MISSION</h3><strong>MEET YOUR TERRITORY</strong><p>Your first objective is to understand the territory and identify the highest-value opportunity.</p><ul class="mission-objectives"><li>○ Identify your assigned territory</li><li>○ Visit your first target farm</li><li>○ Record the commercial opportunity</li></ul><div class="mission-reward">REWARD · +850 XP · TERRITORY PROGRESS</div></div>
      </section>
      <section class="world-control" aria-label="World menu">
        <button class="globe-button" type="button" aria-label="Open world menu"></button><div class="world-label">WORLD<br>MENU</div>
        <nav class="world-menu"><button data-game-view="territory">◎ TERRITORY MAP</button><button data-game-view="farms">◇ MY FARMS</button><button data-game-view="opportunities">◆ OPPORTUNITIES</button><button data-game-view="customers">● CUSTOMERS</button><button data-game-view="missions">★ MISSIONS</button><button data-game-view="training">△ TRAINING</button><button data-game-view="leaderboard">♜ LEADERBOARD</button></nav>
      </section>`;
    document.body.appendChild(hud);
    const mission=hud.querySelector('.mission-hud'); hud.querySelector('.mission-tab').addEventListener('click',()=>mission.classList.toggle('open'));
    const world=hud.querySelector('.world-control'); hud.querySelector('.globe-button').addEventListener('click',()=>world.classList.toggle('open'));
    hud.querySelectorAll('[data-game-view]').forEach(btn=>btn.addEventListener('click',()=>{world.classList.remove('open');const id=btn.dataset.gameView;if(id==='territory') document.getElementById('nationalBtn')?.click();else if(id==='missions') mission.classList.add('open');else if(window.showToast) window.showToast(btn.textContent.trim()+' opened');}));
  }
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',install); else install();
})();
