/* AG WORLD — Dota-style player skill radar. Inspired by the supplied Dota player-stat visual. */
(()=>{
const SKILLS=[
 {key:'technical',name:'TECHNICAL',short:'TECH',icon:'⚙'},
 {key:'operational',name:'OPERATIONAL',short:'OPS',icon:'◈'},
 {key:'product',name:'PRODUCT',short:'PRODUCT',icon:'✦'},
 {key:'management',name:'MANAGEMENT',short:'MGMT',icon:'◆'},
 {key:'people',name:'PEOPLE',short:'PEOPLE',icon:'●'}
];
const MAX=25;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function values(){const v=window.AG_WORLD_SKILL_TOTALS||{};return SKILLS.map(s=>Math.max(0,Math.min(MAX,Number(v[s.key])||0)));}
function polar(cx,cy,r,i){const a=-Math.PI/2+(i*2*Math.PI/SKILLS.length);return [cx+Math.cos(a)*r,cy+Math.sin(a)*r];}
function pts(cx,cy,r,vals){return vals.map((v,i)=>{const p=polar(cx,cy,r*(v/MAX),i);return p.map(n=>n.toFixed(1)).join(',')}).join(' ');}
function grid(cx,cy,r){let out='';for(let level=1;level<=5;level++){const rr=r*level/5;out+=`<polygon points="${SKILLS.map((_,i)=>polar(cx,cy,rr,i).map(n=>n.toFixed(1)).join(',')).join(' ')}"/>`; }return out;}
function axes(cx,cy,r){return SKILLS.map((_,i)=>{const p=polar(cx,cy,r,i);return `<line x1="${cx}" y1="${cy}" x2="${p[0].toFixed(1)}" y2="${p[1].toFixed(1)}"/>`}).join('');}
function labels(cx,cy,r){return SKILLS.map((s,i)=>{const p=polar(cx,cy,r+22,i);const anchor=Math.abs(p[0]-cx)<8?'middle':p[0]<cx?'end':'start';return `<text x="${p[0].toFixed(1)}" y="${p[1].toFixed(1)}" text-anchor="${anchor}">${esc(s.name)}</text>`}).join('');}
function markup(){const vals=values(),total=vals.reduce((a,b)=>a+b,0);return `<section class="ag-skill-tree"><div class="ag-skill-tree-head"><div><span>PLAYER DEVELOPMENT</span><h3>SKILL PROFILE</h3></div><div class="ag-skill-total"><b>${total} ★</b><small>TOTAL SKILL STARS</small></div></div><div class="ag-radar-wrap"><div class="ag-radar-chart"><svg viewBox="0 0 360 300" role="img" aria-label="Player skill profile radar chart"><g class="ag-radar-grid">${grid(160,145,104)}</g><g class="ag-radar-axes">${axes(160,145,104)}</g><polygon class="ag-radar-fill" points="${pts(160,145,104,vals)}"></polygon><polyline class="ag-radar-outline" points="${pts(160,145,104,vals)}"></polyline><g class="ag-radar-points">${vals.map((v,i)=>{const p=polar(160,145,104*(v/MAX),i);return `<circle cx="${p[0].toFixed(1)}" cy="${p[1].toFixed(1)}" r="3.5"></circle>`}).join('')}</g><circle class="ag-radar-center" cx="160" cy="145" r="5"></circle><g class="ag-radar-labels">${labels(160,145,104)}</g></svg></div><div class="ag-radar-stats">${SKILLS.map((s,i)=>`<div class="ag-radar-stat"><span class="ag-radar-icon">${s.icon}</span><div><b>${esc(s.name)}</b><strong>${vals[i]} <em>★</em></strong><small>LEVEL ${vals[i]} / ${MAX}</small></div></div>`).join('')}</div></div><div class="ag-skill-tree-note">Skill profile is built from mission rewards. One mission can advance multiple skills.</div></section>`;}
function render(){const body=document.querySelector('.ag-user-profile-body');if(!body)return;const old=body.querySelector('.ag-skill-tree');if(old)old.remove();body.insertAdjacentHTML('beforeend',markup());}
function css(){if(document.getElementById('ag-dota-skill-style'))return;const s=document.createElement('style');s.id='ag-dota-skill-style';s.textContent=`
.ag-skill-tree{margin-top:16px;border:1px solid #40545c;border-radius:10px;background:#17262d;overflow:hidden;color:#fff;box-shadow:0 8px 24px rgba(18,38,47,.22)}
.ag-skill-tree-head{display:flex;justify-content:space-between;align-items:center;padding:14px 17px;background:linear-gradient(180deg,#263c46,#182a32);border-bottom:1px solid #42545b}.ag-skill-tree-head span{font:900 8px Arial,sans-serif;letter-spacing:1px;color:#9baeb4}.ag-skill-tree-head h3{margin:3px 0 0;font:900 17px Arial,sans-serif}.ag-skill-total{text-align:right}.ag-skill-total b{display:block;font:900 22px Arial,sans-serif;color:#e5b34a}.ag-skill-total small{font:900 7px Arial,sans-serif;color:#9baeb4;letter-spacing:.5px}
.ag-radar-wrap{display:flex;align-items:center;gap:8px;min-height:310px;padding:4px 12px 2px;background:radial-gradient(circle at 32% 48%,rgba(93,130,140,.15),transparent 38%),linear-gradient(120deg,#0e1a20,#1b2c34 52%,#111e24)}.ag-radar-chart{flex:1;min-width:0}.ag-radar-chart svg{display:block;width:100%;height:300px;overflow:visible}.ag-radar-grid polygon{fill:none;stroke:#50636b;stroke-width:1;opacity:.62}.ag-radar-axes line{stroke:#4b5d64;stroke-width:1;opacity:.7}.ag-radar-fill{fill:rgba(184,115,42,.42);stroke:none}.ag-radar-outline{fill:none;stroke:#d5a444;stroke-width:2}.ag-radar-points circle{fill:#d8a642;stroke:#f4d58b;stroke-width:1.5}.ag-radar-center{fill:#a95028;stroke:#d1a05a;stroke-width:1}.ag-radar-labels text{fill:#8fa1a7;font:900 8px Arial,sans-serif;letter-spacing:.6px}.ag-radar-stats{width:42%;max-width:190px;min-width:155px;border-left:1px solid #40535b;padding:5px 0 5px 13px;box-sizing:border-box}.ag-radar-stat{display:grid;grid-template-columns:24px 1fr;align-items:center;gap:6px;padding:7px 5px;border-bottom:1px solid rgba(91,110,117,.34)}.ag-radar-stat:last-child{border-bottom:0}.ag-radar-icon{width:22px;height:22px;display:flex;align-items:center;justify-content:center;border:1px solid #7b6231;background:#263940;color:#e4b34c;font:900 11px Arial,sans-serif}.ag-radar-stat b{display:block;color:#d9e2e4;font:900 8px Arial,sans-serif;white-space:nowrap}.ag-radar-stat strong{display:inline-block;color:#e6b64e;font:900 13px Arial,sans-serif;margin-top:2px}.ag-radar-stat em{font-style:normal}.ag-radar-stat small{display:block;color:#73868d;font:800 6px Arial,sans-serif;margin-top:1px}.ag-skill-tree-note{padding:8px 14px 10px;border-top:1px solid #40525a;background:#15242b;color:#a7b6ba;font:700 8px/1.35 Arial,sans-serif}
@media(max-width:650px){.ag-radar-wrap{display:block;padding:4px 8px 8px}.ag-radar-chart svg{height:275px}.ag-radar-stats{width:100%;max-width:none;display:grid;grid-template-columns:1fr 1fr;border-left:0;border-top:1px solid #40535b;padding:5px 0}.ag-radar-stat{padding:5px}.ag-radar-labels text{font-size:7px}}
`;document.head.appendChild(s);}
function start(){css();render();setTimeout(render,500);setTimeout(render,1500);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
window.AG_WORLD_RENDER_SKILL_TREE=render;
new MutationObserver(()=>{if(document.querySelector('.ag-user-profile-body')&&!document.querySelector('.ag-user-profile-body .ag-skill-tree'))render();}).observe(document.body,{childList:true,subtree:true});
})();