/* AG WORLD — Dota-inspired Skill Tree. Five skill tiers on a central progression spine. */
(()=>{
const SKILLS=[{key:'technical',name:'Technical Knowledge',icon:'⚙'},{key:'operational',name:'Operational Knowledge',icon:'◈'},{key:'product',name:'Product Knowledge',icon:'✦'},{key:'management',name:'Management Skills',icon:'◆'},{key:'people',name:'People Skills',icon:'●'}];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function values(){const v=window.AG_WORLD_SKILL_TOTALS||{};return SKILLS.map(s=>Math.max(0,Number(v[s.key])||0));}
function markup(){const vals=values(),total=vals.reduce((a,b)=>a+b,0);return `<section class="ag-skill-tree"><div class="ag-skill-tree-head"><div><span>PLAYER DEVELOPMENT</span><h3>SKILL TREE</h3></div><div class="ag-skill-total"><b>${total} ★</b><small>TOTAL SKILL STARS</small></div></div><div class="ag-dota-tree" aria-label="Dota-inspired player skill tree"><div class="ag-dota-spine"></div><div class="ag-dota-origin"><b>AG</b><span>WORLD</span></div>${SKILLS.map((s,i)=>{const side=i%2?'right':'left';return `<div class="ag-dota-row ${side} tier-${i}" data-skill="${s.key}"><div class="ag-dota-branch"></div><div class="ag-dota-tier">${i+1}</div><div class="ag-dota-skill-card"><div class="ag-dota-icon">${s.icon}</div><div class="ag-dota-copy"><b>${esc(s.name)}</b><span>${vals[i]} <em>★</em> EARNED</span><div class="ag-dota-progress"><i style="width:${Math.min(100,Math.round(vals[i]/25*100))}%"></i></div><small>LEVEL ${Math.min(25,vals[i])} / 25</small></div></div></div>`;}).join('')}</div><div class="ag-skill-tree-note">Complete missions to earn skill stars. Multiple skills can advance from one mission.</div></section>`;}
function render(){const body=document.querySelector('.ag-user-profile-body');if(!body||body.querySelector('.ag-skill-tree'))return;body.insertAdjacentHTML('beforeend',markup());}
function refresh(){const tree=document.querySelector('.ag-user-profile-body .ag-skill-tree');if(!tree)return;const vals=values();tree.querySelector('.ag-skill-total b').textContent=vals.reduce((a,b)=>a+b,0)+' ★';SKILLS.forEach((s,i)=>{const n=tree.querySelector(`[data-skill="${s.key}"]`);if(!n)return;n.querySelector('.ag-dota-copy span').innerHTML=`${vals[i]} <em>★</em> EARNED`;n.querySelector('.ag-dota-progress i').style.width=Math.min(100,Math.round(vals[i]/25*100))+'%';n.querySelector('.ag-dota-copy small').textContent=`LEVEL ${Math.min(25,vals[i])} / 25`;});}
function css(){if(document.getElementById('ag-dota-skill-style'))return;const s=document.createElement('style');s.id='ag-dota-skill-style';s.textContent=`
.ag-skill-tree{margin-top:16px;border:1px solid #d4dee1;border-radius:10px;background:#182830;overflow:hidden;color:#fff;box-shadow:0 8px 24px rgba(18,38,47,.18)}
.ag-skill-tree-head{display:flex;justify-content:space-between;align-items:center;padding:14px 17px;background:linear-gradient(180deg,#263c46,#1a2c34);border-bottom:1px solid #42545b}.ag-skill-tree-head span{font:900 8px Arial,sans-serif;letter-spacing:1px;color:#9baeb4}.ag-skill-tree-head h3{margin:3px 0 0;font:900 17px Arial,sans-serif}.ag-skill-total{text-align:right}.ag-skill-total b{display:block;font:900 21px Arial,sans-serif;color:#e5b34a}.ag-skill-total small{font:900 7px Arial,sans-serif;color:#9baeb4;letter-spacing:.5px}
.ag-dota-tree{position:relative;height:390px;padding:10px 8px 8px;box-sizing:border-box;background:radial-gradient(circle at 50% 50%,rgba(91,129,138,.18),transparent 42%),linear-gradient(90deg,rgba(10,20,25,.4),rgba(32,48,55,.15),rgba(10,20,25,.4));overflow:hidden}.ag-dota-spine{position:absolute;left:50%;top:42px;bottom:22px;width:3px;transform:translateX(-50%);background:linear-gradient(#8c6330,#e1ae45 35%,#8c6330);box-shadow:0 0 8px rgba(225,174,69,.3);z-index:1}.ag-dota-origin{position:absolute;left:50%;top:8px;transform:translateX(-50%);width:48px;height:48px;border-radius:50%;background:radial-gradient(circle at 35% 30%,#405963,#132630 65%);border:3px solid #d9a842;box-shadow:0 4px 14px rgba(0,0,0,.5);z-index:5;display:flex;flex-direction:column;align-items:center;justify-content:center}.ag-dota-origin b{font:900 15px Arial,sans-serif}.ag-dota-origin span{font:900 5px Arial,sans-serif;letter-spacing:.7px;color:#d8a942}
.ag-dota-row{position:absolute;left:0;right:0;height:58px;z-index:3}.ag-dota-row.tier-0{top:66px}.ag-dota-row.tier-1{top:130px}.ag-dota-row.tier-2{top:194px}.ag-dota-row.tier-3{top:258px}.ag-dota-row.tier-4{top:322px}.ag-dota-tier{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);width:30px;height:30px;border-radius:50%;background:radial-gradient(circle at 35% 30%,#f4cb70,#a86d20 65%,#533915);border:2px solid #f1d08b;box-shadow:0 3px 8px rgba(0,0,0,.5);display:flex;align-items:center;justify-content:center;color:#1b2529;font:900 12px Arial,sans-serif;z-index:6}.ag-dota-branch{position:absolute;top:50%;width:calc(50% - 16px);height:2px;background:linear-gradient(90deg,#596c72,#c89a45);opacity:.8}.ag-dota-row.left .ag-dota-branch{right:calc(50% + 16px)}.ag-dota-row.right .ag-dota-branch{left:calc(50% + 16px);background:linear-gradient(90deg,#c89a45,#596c72)}
.ag-dota-skill-card{position:absolute;top:50%;transform:translateY(-50%);width:43%;min-height:50px;padding:6px 8px;box-sizing:border-box;border:1px solid #566970;background:linear-gradient(180deg,#263a42,#1c2d34);box-shadow:0 4px 10px rgba(0,0,0,.35);display:flex;align-items:center;gap:7px}.ag-dota-row.left .ag-dota-skill-card{right:54%}.ag-dota-row.right .ag-dota-skill-card{left:54%}.ag-dota-icon{flex:0 0 31px;width:31px;height:31px;border:2px solid #9b7430;border-radius:4px;background:linear-gradient(145deg,#47616b,#18262d);display:flex;align-items:center;justify-content:center;font:900 15px Arial,sans-serif;color:#e8c26a;box-shadow:inset 1px 1px 2px rgba(255,255,255,.12),3px 3px 5px rgba(0,0,0,.35)}.ag-dota-copy{min-width:0;flex:1}.ag-dota-copy b{display:block;font:900 10px/1.1 Arial,sans-serif;color:#eef3f4;white-space:nowrap}.ag-dota-copy span{display:block;margin-top:2px;font:900 9px/1 Arial,sans-serif;color:#e4b348}.ag-dota-copy em{font-style:normal;color:#f3c95d}.ag-dota-progress{height:4px;margin-top:4px;background:#0d171c;border:1px solid #43545a}.ag-dota-progress i{display:block;height:100%;background:linear-gradient(90deg,#5d9e4e,#b5d766)}.ag-dota-copy small{display:block;margin-top:2px;color:#93a6ad;font:800 6px Arial,sans-serif;letter-spacing:.3px}.ag-skill-tree-note{padding:8px 14px 10px;border-top:1px solid #40525a;background:#15242b;color:#a7b6ba;font:700 8px/1.35 Arial,sans-serif}
@media(max-width:650px){.ag-dota-tree{height:350px}.ag-dota-skill-card{width:41%;padding:5px}.ag-dota-copy b{font-size:8px}.ag-dota-copy span{font-size:8px}.ag-dota-icon{width:27px;height:27px;flex-basis:27px}.ag-dota-tier{width:27px;height:27px}}
`;document.head.appendChild(s);}
function start(){css();render();refresh();setTimeout(render,500);setTimeout(render,1500);}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();window.AG_WORLD_RENDER_SKILL_TREE=()=>{render();refresh();};new MutationObserver(()=>{if(document.querySelector('.ag-user-profile-body')&&!document.querySelector('.ag-user-profile-body .ag-skill-tree'))render();}).observe(document.body,{childList:true,subtree:true});})();
